/*
 * generated by Xtext 2.41.0
 */
package lu.list.swrdi.formulaKPI.ide;


/**
 * Use this class to register ide components.
 */
public class KPIFormulaDSLIdeModule extends AbstractKPIFormulaDSLIdeModule {
}
