/*
 * generated by Xtext 2.41.0
 */
package lu.list.swrdi.formulaKPI.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import lu.list.swrdi.formulaKPI.KPIFormulaDSLRuntimeModule;
import lu.list.swrdi.formulaKPI.KPIFormulaDSLStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class KPIFormulaDSLIdeSetup extends KPIFormulaDSLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new KPIFormulaDSLRuntimeModule(), new KPIFormulaDSLIdeModule()));
	}
	
}
