/*
 * generated by Xtext 2.41.0
 */
package lu.list.swrdi.formulaKPI.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractKPIFormulaDSLScopeProvider extends DelegatingScopeProvider {
}
