/*
 * generated by Xtext 2.41.0
 */
package lu.list.swrdi.formulaKPI.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class KPIFormulaDSLGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class KPIFormulaDSLElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "lu.list.swrdi.formulaKPI.KPIFormulaDSL.KPIFormulaDSL");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cDeclarationsAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cDeclarationsDeclarationParserRuleCall_0_0 = (RuleCall)cDeclarationsAssignment_0.eContents().get(0);
		private final Assignment cComputationsAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cComputationsComputationParserRuleCall_1_0 = (RuleCall)cComputationsAssignment_1.eContents().get(0);
		
		//KPIFormulaDSL returns KPIFormula: declarations+=Declaration+ computations+=Computation+;
		@Override public ParserRule getRule() { return rule; }
		
		//declarations+=Declaration+ computations+=Computation+
		public Group getGroup() { return cGroup; }
		
		//declarations+=Declaration+
		public Assignment getDeclarationsAssignment_0() { return cDeclarationsAssignment_0; }
		
		//Declaration
		public RuleCall getDeclarationsDeclarationParserRuleCall_0_0() { return cDeclarationsDeclarationParserRuleCall_0_0; }
		
		//computations+=Computation+
		public Assignment getComputationsAssignment_1() { return cComputationsAssignment_1; }
		
		//Computation
		public RuleCall getComputationsComputationParserRuleCall_1_0() { return cComputationsComputationParserRuleCall_1_0; }
	}
	public class DeclarationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "lu.list.swrdi.formulaKPI.KPIFormulaDSL.Declaration");
		private final Assignment cDeclaredAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cDeclaredDeclarableParserRuleCall_0 = (RuleCall)cDeclaredAssignment.eContents().get(0);
		
		//Declaration returns Declaration: declared=Declarable;
		@Override public ParserRule getRule() { return rule; }
		
		//declared=Declarable
		public Assignment getDeclaredAssignment() { return cDeclaredAssignment; }
		
		//Declarable
		public RuleCall getDeclaredDeclarableParserRuleCall_0() { return cDeclaredDeclarableParserRuleCall_0; }
	}
	public class ComputationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "lu.list.swrdi.formulaKPI.KPIFormulaDSL.Computation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cComputedAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cComputedComputableCrossReference_0_0 = (CrossReference)cComputedAssignment_0.eContents().get(0);
		private final RuleCall cComputedComputableIDTerminalRuleCall_0_0_1 = (RuleCall)cComputedComputableCrossReference_0_0.eContents().get(1);
		private final Keyword cEqualsSignKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cFormulaAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final Alternatives cFormulaAlternatives_2_0 = (Alternatives)cFormulaAssignment_2.eContents().get(0);
		private final RuleCall cFormulaExpressionParserRuleCall_2_0_0 = (RuleCall)cFormulaAlternatives_2_0.eContents().get(0);
		private final RuleCall cFormulaConditionParserRuleCall_2_0_1 = (RuleCall)cFormulaAlternatives_2_0.eContents().get(1);
		
		//Computation returns Computation: computed=[Computable] "=" formula=(Expression|Condition);
		@Override public ParserRule getRule() { return rule; }
		
		//computed=[Computable] "=" formula=(Expression|Condition)
		public Group getGroup() { return cGroup; }
		
		//computed=[Computable]
		public Assignment getComputedAssignment_0() { return cComputedAssignment_0; }
		
		//[Computable]
		public CrossReference getComputedComputableCrossReference_0_0() { return cComputedComputableCrossReference_0_0; }
		
		//ID
		public RuleCall getComputedComputableIDTerminalRuleCall_0_0_1() { return cComputedComputableIDTerminalRuleCall_0_0_1; }
		
		//"="
		public Keyword getEqualsSignKeyword_1() { return cEqualsSignKeyword_1; }
		
		//formula=(Expression|Condition)
		public Assignment getFormulaAssignment_2() { return cFormulaAssignment_2; }
		
		//(Expression|Condition)
		public Alternatives getFormulaAlternatives_2_0() { return cFormulaAlternatives_2_0; }
		
		//Expression
		public RuleCall getFormulaExpressionParserRuleCall_2_0_0() { return cFormulaExpressionParserRuleCall_2_0_0; }
		
		//Condition
		public RuleCall getFormulaConditionParserRuleCall_2_0_1() { return cFormulaConditionParserRuleCall_2_0_1; }
	}
	public class DeclarableElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "lu.list.swrdi.formulaKPI.KPIFormulaDSL.Declarable");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cKPIParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cMetricParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Declarable returns Declarable: KPI | Metric;
		@Override public ParserRule getRule() { return rule; }
		
		//KPI | Metric
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//KPI
		public RuleCall getKPIParserRuleCall_0() { return cKPIParserRuleCall_0; }
		
		//Metric
		public RuleCall getMetricParserRuleCall_1() { return cMetricParserRuleCall_1; }
	}
	public class MetricElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "lu.list.swrdi.formulaKPI.KPIFormulaDSL.Metric");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cOfKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cTypeKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cTypeAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cTypeValueTypeParserRuleCall_3_0 = (RuleCall)cTypeAssignment_3.eContents().get(0);
		
		//Metric returns Metric: name=ID "of" "type" type=ValueType;
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID "of" "type" type=ValueType
		public Group getGroup() { return cGroup; }
		
		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }
		
		//"of"
		public Keyword getOfKeyword_1() { return cOfKeyword_1; }
		
		//"type"
		public Keyword getTypeKeyword_2() { return cTypeKeyword_2; }
		
		//type=ValueType
		public Assignment getTypeAssignment_3() { return cTypeAssignment_3; }
		
		//ValueType
		public RuleCall getTypeValueTypeParserRuleCall_3_0() { return cTypeValueTypeParserRuleCall_3_0; }
	}
	public class KPIElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "lu.list.swrdi.formulaKPI.KPIFormulaDSL.KPI");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cKPIKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cOfKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cTypeKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cTypeAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cTypeValueTypeParserRuleCall_4_0 = (RuleCall)cTypeAssignment_4.eContents().get(0);
		
		//KPI returns KPI: "KPI" name=ID "of" "type" type=ValueType;
		@Override public ParserRule getRule() { return rule; }
		
		//"KPI" name=ID "of" "type" type=ValueType
		public Group getGroup() { return cGroup; }
		
		//"KPI"
		public Keyword getKPIKeyword_0() { return cKPIKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//"of"
		public Keyword getOfKeyword_2() { return cOfKeyword_2; }
		
		//"type"
		public Keyword getTypeKeyword_3() { return cTypeKeyword_3; }
		
		//type=ValueType
		public Assignment getTypeAssignment_4() { return cTypeAssignment_4; }
		
		//ValueType
		public RuleCall getTypeValueTypeParserRuleCall_4_0() { return cTypeValueTypeParserRuleCall_4_0; }
	}
	public class ValueTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "lu.list.swrdi.formulaKPI.KPIFormulaDSL.ValueType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cIntegerValueParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cRealValueParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cTextualValueParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cBooleanValueParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cEnumerationValueParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cAggregationValueParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		private final RuleCall cDriftValueParserRuleCall_6 = (RuleCall)cAlternatives.eContents().get(6);
		private final RuleCall cUnitValueParserRuleCall_7 = (RuleCall)cAlternatives.eContents().get(7);
		
		//ValueType returns ValueType:
		//    IntegerValue | RealValue | TextualValue | BooleanValue |
		//    EnumerationValue | AggregationValue | DriftValue | UnitValue
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//IntegerValue | RealValue | TextualValue | BooleanValue |
		//EnumerationValue | AggregationValue | DriftValue | UnitValue
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//IntegerValue
		public RuleCall getIntegerValueParserRuleCall_0() { return cIntegerValueParserRuleCall_0; }
		
		//RealValue
		public RuleCall getRealValueParserRuleCall_1() { return cRealValueParserRuleCall_1; }
		
		//TextualValue
		public RuleCall getTextualValueParserRuleCall_2() { return cTextualValueParserRuleCall_2; }
		
		//BooleanValue
		public RuleCall getBooleanValueParserRuleCall_3() { return cBooleanValueParserRuleCall_3; }
		
		//EnumerationValue
		public RuleCall getEnumerationValueParserRuleCall_4() { return cEnumerationValueParserRuleCall_4; }
		
		//AggregationValue
		public RuleCall getAggregationValueParserRuleCall_5() { return cAggregationValueParserRuleCall_5; }
		
		//DriftValue
		public RuleCall getDriftValueParserRuleCall_6() { return cDriftValueParserRuleCall_6; }
		
		//UnitValue
		public RuleCall getUnitValueParserRuleCall_7() { return cUnitValueParserRuleCall_7; }
	}
	public class IntegerValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "lu.list.swrdi.formulaKPI.KPIFormulaDSL.IntegerValue");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cIntegerValueAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cIntKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//IntegerValue : {IntegerValue} "int";
		@Override public ParserRule getRule() { return rule; }
		
		//{IntegerValue} "int"
		public Group getGroup() { return cGroup; }
		
		//{IntegerValue}
		public Action getIntegerValueAction_0() { return cIntegerValueAction_0; }
		
		//"int"
		public Keyword getIntKeyword_1() { return cIntKeyword_1; }
	}
	public class RealValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "lu.list.swrdi.formulaKPI.KPIFormulaDSL.RealValue");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRealValueAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cRealKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//RealValue: {RealValue} "real";
		@Override public ParserRule getRule() { return rule; }
		
		//{RealValue} "real"
		public Group getGroup() { return cGroup; }
		
		//{RealValue}
		public Action getRealValueAction_0() { return cRealValueAction_0; }
		
		//"real"
		public Keyword getRealKeyword_1() { return cRealKeyword_1; }
	}
	public class TextualValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "lu.list.swrdi.formulaKPI.KPIFormulaDSL.TextualValue");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cTextualValueAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cTextKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//TextualValue: {TextualValue} "text";
		@Override public ParserRule getRule() { return rule; }
		
		//{TextualValue} "text"
		public Group getGroup() { return cGroup; }
		
		//{TextualValue}
		public Action getTextualValueAction_0() { return cTextualValueAction_0; }
		
		//"text"
		public Keyword getTextKeyword_1() { return cTextKeyword_1; }
	}
	public class BooleanValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "lu.list.swrdi.formulaKPI.KPIFormulaDSL.BooleanValue");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cBooleanValueAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cBoolKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//BooleanValue: {BooleanValue} "bool";
		@Override public ParserRule getRule() { return rule; }
		
		//{BooleanValue} "bool"
		public Group getGroup() { return cGroup; }
		
		//{BooleanValue}
		public Action getBooleanValueAction_0() { return cBooleanValueAction_0; }
		
		//"bool"
		public Keyword getBoolKeyword_1() { return cBoolKeyword_1; }
	}
	public class EnumerationValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "lu.list.swrdi.formulaKPI.KPIFormulaDSL.EnumerationValue");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cLiteralsAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cLiteralsEnumerationLiteralParserRuleCall_1_0 = (RuleCall)cLiteralsAssignment_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//EnumerationValue returns EnumerationValue: "{" literals+=EnumerationLiteral+ "}";
		@Override public ParserRule getRule() { return rule; }
		
		//"{" literals+=EnumerationLiteral+ "}"
		public Group getGroup() { return cGroup; }
		
		//"{"
		public Keyword getLeftCurlyBracketKeyword_0() { return cLeftCurlyBracketKeyword_0; }
		
		//literals+=EnumerationLiteral+
		public Assignment getLiteralsAssignment_1() { return cLiteralsAssignment_1; }
		
		//EnumerationLiteral
		public RuleCall getLiteralsEnumerationLiteralParserRuleCall_1_0() { return cLiteralsEnumerationLiteralParserRuleCall_1_0; }
		
		//"}"
		public Keyword getRightCurlyBracketKeyword_2() { return cRightCurlyBracketKeyword_2; }
	}
	public class EnumerationLiteralElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "lu.list.swrdi.formulaKPI.KPIFormulaDSL.EnumerationLiteral");
		private final Assignment cNameAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_0 = (RuleCall)cNameAssignment.eContents().get(0);
		
		//EnumerationLiteral returns EnumerationLiteral: name=ID;
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID
		public Assignment getNameAssignment() { return cNameAssignment; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0() { return cNameIDTerminalRuleCall_0; }
	}
	public class UnitValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "lu.list.swrdi.formulaKPI.KPIFormulaDSL.UnitValue");
		private final Assignment cUnitAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cUnitValueUnitEnumRuleCall_0 = (RuleCall)cUnitAssignment.eContents().get(0);
		
		//UnitValue returns UnitValue: unit=ValueUnit;
		@Override public ParserRule getRule() { return rule; }
		
		//unit=ValueUnit
		public Assignment getUnitAssignment() { return cUnitAssignment; }
		
		//ValueUnit
		public RuleCall getUnitValueUnitEnumRuleCall_0() { return cUnitValueUnitEnumRuleCall_0; }
	}
	public class AggregationValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "lu.list.swrdi.formulaKPI.KPIFormulaDSL.AggregationValue");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAggregateKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cOperationAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cOperationOperationParserRuleCall_1_0 = (RuleCall)cOperationAssignment_1.eContents().get(0);
		private final Keyword cForKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cWindowAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cWindowINTTerminalRuleCall_3_0 = (RuleCall)cWindowAssignment_3.eContents().get(0);
		private final Assignment cWindowUnitAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cWindowUnitWindowUnitEnumRuleCall_4_0 = (RuleCall)cWindowUnitAssignment_4.eContents().get(0);
		
		//AggregationValue returns AggregationValue: "aggregate" operation=Operation "for" window=INT windowUnit=WindowUnit;
		@Override public ParserRule getRule() { return rule; }
		
		//"aggregate" operation=Operation "for" window=INT windowUnit=WindowUnit
		public Group getGroup() { return cGroup; }
		
		//"aggregate"
		public Keyword getAggregateKeyword_0() { return cAggregateKeyword_0; }
		
		//operation=Operation
		public Assignment getOperationAssignment_1() { return cOperationAssignment_1; }
		
		//Operation
		public RuleCall getOperationOperationParserRuleCall_1_0() { return cOperationOperationParserRuleCall_1_0; }
		
		//"for"
		public Keyword getForKeyword_2() { return cForKeyword_2; }
		
		//window=INT
		public Assignment getWindowAssignment_3() { return cWindowAssignment_3; }
		
		//INT
		public RuleCall getWindowINTTerminalRuleCall_3_0() { return cWindowINTTerminalRuleCall_3_0; }
		
		//windowUnit=WindowUnit
		public Assignment getWindowUnitAssignment_4() { return cWindowUnitAssignment_4; }
		
		//WindowUnit
		public RuleCall getWindowUnitWindowUnitEnumRuleCall_4_0() { return cWindowUnitWindowUnitEnumRuleCall_4_0; }
	}
	public class DriftValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "lu.list.swrdi.formulaKPI.KPIFormulaDSL.DriftValue");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cDriftKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cOfKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cOperationAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cOperationOperationParserRuleCall_2_0 = (RuleCall)cOperationAssignment_2.eContents().get(0);
		private final Keyword cForKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cWindowAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cWindowINTTerminalRuleCall_4_0 = (RuleCall)cWindowAssignment_4.eContents().get(0);
		private final Assignment cWindowUnitAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cWindowUnitWindowUnitEnumRuleCall_5_0 = (RuleCall)cWindowUnitAssignment_5.eContents().get(0);
		
		//DriftValue returns DriftValue: "drift" "of" operation=Operation "for" window=INT windowUnit=WindowUnit;
		@Override public ParserRule getRule() { return rule; }
		
		//"drift" "of" operation=Operation "for" window=INT windowUnit=WindowUnit
		public Group getGroup() { return cGroup; }
		
		//"drift"
		public Keyword getDriftKeyword_0() { return cDriftKeyword_0; }
		
		//"of"
		public Keyword getOfKeyword_1() { return cOfKeyword_1; }
		
		//operation=Operation
		public Assignment getOperationAssignment_2() { return cOperationAssignment_2; }
		
		//Operation
		public RuleCall getOperationOperationParserRuleCall_2_0() { return cOperationOperationParserRuleCall_2_0; }
		
		//"for"
		public Keyword getForKeyword_3() { return cForKeyword_3; }
		
		//window=INT
		public Assignment getWindowAssignment_4() { return cWindowAssignment_4; }
		
		//INT
		public RuleCall getWindowINTTerminalRuleCall_4_0() { return cWindowINTTerminalRuleCall_4_0; }
		
		//windowUnit=WindowUnit
		public Assignment getWindowUnitAssignment_5() { return cWindowUnitAssignment_5; }
		
		//WindowUnit
		public RuleCall getWindowUnitWindowUnitEnumRuleCall_5_0() { return cWindowUnitWindowUnitEnumRuleCall_5_0; }
	}
	public class OperationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "lu.list.swrdi.formulaKPI.KPIFormulaDSL.Operation");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cMinimumParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cMaximumParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cAverageParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cMedianParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cStandardDeviationParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		
		//Operation returns Operation:
		//    Minimum | Maximum | Average | Median | StandardDeviation
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//Minimum | Maximum | Average | Median | StandardDeviation
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Minimum
		public RuleCall getMinimumParserRuleCall_0() { return cMinimumParserRuleCall_0; }
		
		//Maximum
		public RuleCall getMaximumParserRuleCall_1() { return cMaximumParserRuleCall_1; }
		
		//Average
		public RuleCall getAverageParserRuleCall_2() { return cAverageParserRuleCall_2; }
		
		//Median
		public RuleCall getMedianParserRuleCall_3() { return cMedianParserRuleCall_3; }
		
		//StandardDeviation
		public RuleCall getStandardDeviationParserRuleCall_4() { return cStandardDeviationParserRuleCall_4; }
	}
	public class MinimumElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "lu.list.swrdi.formulaKPI.KPIFormulaDSL.Minimum");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cMinimumAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cMinimumKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//Minimum: {Minimum} "Minimum";
		@Override public ParserRule getRule() { return rule; }
		
		//{Minimum} "Minimum"
		public Group getGroup() { return cGroup; }
		
		//{Minimum}
		public Action getMinimumAction_0() { return cMinimumAction_0; }
		
		//"Minimum"
		public Keyword getMinimumKeyword_1() { return cMinimumKeyword_1; }
	}
	public class MaximumElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "lu.list.swrdi.formulaKPI.KPIFormulaDSL.Maximum");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cMaximumAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cMaximumKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//Maximum: {Maximum} "Maximum";
		@Override public ParserRule getRule() { return rule; }
		
		//{Maximum} "Maximum"
		public Group getGroup() { return cGroup; }
		
		//{Maximum}
		public Action getMaximumAction_0() { return cMaximumAction_0; }
		
		//"Maximum"
		public Keyword getMaximumKeyword_1() { return cMaximumKeyword_1; }
	}
	public class AverageElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "lu.list.swrdi.formulaKPI.KPIFormulaDSL.Average");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cAverageAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cAverageKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//Average: {Average} "Average";
		@Override public ParserRule getRule() { return rule; }
		
		//{Average} "Average"
		public Group getGroup() { return cGroup; }
		
		//{Average}
		public Action getAverageAction_0() { return cAverageAction_0; }
		
		//"Average"
		public Keyword getAverageKeyword_1() { return cAverageKeyword_1; }
	}
	public class MedianElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "lu.list.swrdi.formulaKPI.KPIFormulaDSL.Median");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cMedianAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cMedianKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//Median: {Median} "Median";
		@Override public ParserRule getRule() { return rule; }
		
		//{Median} "Median"
		public Group getGroup() { return cGroup; }
		
		//{Median}
		public Action getMedianAction_0() { return cMedianAction_0; }
		
		//"Median"
		public Keyword getMedianKeyword_1() { return cMedianKeyword_1; }
	}
	public class StandardDeviationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "lu.list.swrdi.formulaKPI.KPIFormulaDSL.StandardDeviation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cStandardDeviationAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cStandardKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cDeviationKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//StandardDeviation: {StandardDeviation} "Standard" "deviation";
		@Override public ParserRule getRule() { return rule; }
		
		//{StandardDeviation} "Standard" "deviation"
		public Group getGroup() { return cGroup; }
		
		//{StandardDeviation}
		public Action getStandardDeviationAction_0() { return cStandardDeviationAction_0; }
		
		//"Standard"
		public Keyword getStandardKeyword_1() { return cStandardKeyword_1; }
		
		//"deviation"
		public Keyword getDeviationKeyword_2() { return cDeviationKeyword_2; }
	}
	public class ConditionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "lu.list.swrdi.formulaKPI.KPIFormulaDSL.Condition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Assignment cConditionsAssignment_1_0 = (Assignment)cGroup_1.eContents().get(0);
		private final RuleCall cConditionsExpressionParserRuleCall_1_0_0 = (RuleCall)cConditionsAssignment_1_0.eContents().get(0);
		private final Keyword cHyphenMinusGreaterThanSignKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final Assignment cResultsAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cResultsExpressionParserRuleCall_1_2_0 = (RuleCall)cResultsAssignment_1_2.eContents().get(0);
		private final Keyword cSemicolonKeyword_1_3 = (Keyword)cGroup_1.eContents().get(3);
		private final Keyword cOtherwiseKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cHyphenMinusGreaterThanSignKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cResultsAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cResultsExpressionParserRuleCall_4_0 = (RuleCall)cResultsAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Condition returns ConditionalOp:
		//    "{"
		//        (conditions+=Expression "->" results+=Expression  ";")+
		//        => "otherwise" "->" results+=Expression
		//    "}"
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//"{"
		//    (conditions+=Expression "->" results+=Expression  ";")+
		//    => "otherwise" "->" results+=Expression
		//"}"
		public Group getGroup() { return cGroup; }
		
		//"{"
		public Keyword getLeftCurlyBracketKeyword_0() { return cLeftCurlyBracketKeyword_0; }
		
		//(conditions+=Expression "->" results+=Expression  ";")+
		public Group getGroup_1() { return cGroup_1; }
		
		//conditions+=Expression
		public Assignment getConditionsAssignment_1_0() { return cConditionsAssignment_1_0; }
		
		//Expression
		public RuleCall getConditionsExpressionParserRuleCall_1_0_0() { return cConditionsExpressionParserRuleCall_1_0_0; }
		
		//"->"
		public Keyword getHyphenMinusGreaterThanSignKeyword_1_1() { return cHyphenMinusGreaterThanSignKeyword_1_1; }
		
		//results+=Expression
		public Assignment getResultsAssignment_1_2() { return cResultsAssignment_1_2; }
		
		//Expression
		public RuleCall getResultsExpressionParserRuleCall_1_2_0() { return cResultsExpressionParserRuleCall_1_2_0; }
		
		//";"
		public Keyword getSemicolonKeyword_1_3() { return cSemicolonKeyword_1_3; }
		
		//=> "otherwise"
		public Keyword getOtherwiseKeyword_2() { return cOtherwiseKeyword_2; }
		
		//"->"
		public Keyword getHyphenMinusGreaterThanSignKeyword_3() { return cHyphenMinusGreaterThanSignKeyword_3; }
		
		//results+=Expression
		public Assignment getResultsAssignment_4() { return cResultsAssignment_4; }
		
		//Expression
		public RuleCall getResultsExpressionParserRuleCall_4_0() { return cResultsExpressionParserRuleCall_4_0; }
		
		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class ExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "lu.list.swrdi.formulaKPI.KPIFormulaDSL.Expression");
		private final RuleCall cOrParserRuleCall = (RuleCall)rule.eContents().get(1);
		
		//Expression returns Expression: Or;
		@Override public ParserRule getRule() { return rule; }
		
		//Or
		public RuleCall getOrParserRuleCall() { return cOrParserRuleCall; }
	}
	public class OrElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "lu.list.swrdi.formulaKPI.KPIFormulaDSL.Or");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cAndParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cOrLeftAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Keyword cOrKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final Assignment cRightAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cRightAndParserRuleCall_1_2_0 = (RuleCall)cRightAssignment_1_2.eContents().get(0);
		
		//Or returns Expression:
		//    And (
		//        {Or.left=current} "or" right=And
		//    )*;
		@Override public ParserRule getRule() { return rule; }
		
		//And (
		//    {Or.left=current} "or" right=And
		//)*
		public Group getGroup() { return cGroup; }
		
		//And
		public RuleCall getAndParserRuleCall_0() { return cAndParserRuleCall_0; }
		
		//(
		//       {Or.left=current} "or" right=And
		//   )*
		public Group getGroup_1() { return cGroup_1; }
		
		//{Or.left=current}
		public Action getOrLeftAction_1_0() { return cOrLeftAction_1_0; }
		
		//"or"
		public Keyword getOrKeyword_1_1() { return cOrKeyword_1_1; }
		
		//right=And
		public Assignment getRightAssignment_1_2() { return cRightAssignment_1_2; }
		
		//And
		public RuleCall getRightAndParserRuleCall_1_2_0() { return cRightAndParserRuleCall_1_2_0; }
	}
	public class AndElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "lu.list.swrdi.formulaKPI.KPIFormulaDSL.And");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cEqualityParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cAndLeftAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Keyword cAndKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final Assignment cRightAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cRightEqualityParserRuleCall_1_2_0 = (RuleCall)cRightAssignment_1_2.eContents().get(0);
		
		//And returns Expression:
		//    Equality (
		//        {And.left=current} "and" right=Equality
		//    )*;
		@Override public ParserRule getRule() { return rule; }
		
		//Equality (
		//    {And.left=current} "and" right=Equality
		//)*
		public Group getGroup() { return cGroup; }
		
		//Equality
		public RuleCall getEqualityParserRuleCall_0() { return cEqualityParserRuleCall_0; }
		
		//(
		//       {And.left=current} "and" right=Equality
		//   )*
		public Group getGroup_1() { return cGroup_1; }
		
		//{And.left=current}
		public Action getAndLeftAction_1_0() { return cAndLeftAction_1_0; }
		
		//"and"
		public Keyword getAndKeyword_1_1() { return cAndKeyword_1_1; }
		
		//right=Equality
		public Assignment getRightAssignment_1_2() { return cRightAssignment_1_2; }
		
		//Equality
		public RuleCall getRightEqualityParserRuleCall_1_2_0() { return cRightEqualityParserRuleCall_1_2_0; }
	}
	public class EqualityElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "lu.list.swrdi.formulaKPI.KPIFormulaDSL.Equality");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cComparisonParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Alternatives cAlternatives_1_0 = (Alternatives)cGroup_1.eContents().get(0);
		private final Group cGroup_1_0_0 = (Group)cAlternatives_1_0.eContents().get(0);
		private final Action cEqualityLeftAction_1_0_0_0 = (Action)cGroup_1_0_0.eContents().get(0);
		private final Keyword cEqualsSignEqualsSignKeyword_1_0_0_1 = (Keyword)cGroup_1_0_0.eContents().get(1);
		private final Group cGroup_1_0_1 = (Group)cAlternatives_1_0.eContents().get(1);
		private final Action cInequalityLeftAction_1_0_1_0 = (Action)cGroup_1_0_1.eContents().get(0);
		private final Keyword cExclamationMarkEqualsSignKeyword_1_0_1_1 = (Keyword)cGroup_1_0_1.eContents().get(1);
		private final Assignment cRightAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cRightComparisonParserRuleCall_1_1_0 = (RuleCall)cRightAssignment_1_1.eContents().get(0);
		
		//Equality returns Expression:
		//    Comparison (
		//        ({Equality.left=current} '==' | {Inequality.left=current} '!=')
		//        right=Comparison
		//    )*;
		@Override public ParserRule getRule() { return rule; }
		
		//Comparison (
		//    ({Equality.left=current} '==' | {Inequality.left=current} '!=')
		//    right=Comparison
		//)*
		public Group getGroup() { return cGroup; }
		
		//Comparison
		public RuleCall getComparisonParserRuleCall_0() { return cComparisonParserRuleCall_0; }
		
		//(
		//       ({Equality.left=current} '==' | {Inequality.left=current} '!=')
		//       right=Comparison
		//   )*
		public Group getGroup_1() { return cGroup_1; }
		
		//({Equality.left=current} '==' | {Inequality.left=current} '!=')
		public Alternatives getAlternatives_1_0() { return cAlternatives_1_0; }
		
		//{Equality.left=current} '=='
		public Group getGroup_1_0_0() { return cGroup_1_0_0; }
		
		//{Equality.left=current}
		public Action getEqualityLeftAction_1_0_0_0() { return cEqualityLeftAction_1_0_0_0; }
		
		//'=='
		public Keyword getEqualsSignEqualsSignKeyword_1_0_0_1() { return cEqualsSignEqualsSignKeyword_1_0_0_1; }
		
		//{Inequality.left=current} '!='
		public Group getGroup_1_0_1() { return cGroup_1_0_1; }
		
		//{Inequality.left=current}
		public Action getInequalityLeftAction_1_0_1_0() { return cInequalityLeftAction_1_0_1_0; }
		
		//'!='
		public Keyword getExclamationMarkEqualsSignKeyword_1_0_1_1() { return cExclamationMarkEqualsSignKeyword_1_0_1_1; }
		
		//right=Comparison
		public Assignment getRightAssignment_1_1() { return cRightAssignment_1_1; }
		
		//Comparison
		public RuleCall getRightComparisonParserRuleCall_1_1_0() { return cRightComparisonParserRuleCall_1_1_0; }
	}
	public class ComparisonElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "lu.list.swrdi.formulaKPI.KPIFormulaDSL.Comparison");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cPlusOrMinusParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Alternatives cAlternatives_1_0 = (Alternatives)cGroup_1.eContents().get(0);
		private final Group cGroup_1_0_0 = (Group)cAlternatives_1_0.eContents().get(0);
		private final Action cGreaterEqLeftAction_1_0_0_0 = (Action)cGroup_1_0_0.eContents().get(0);
		private final Keyword cGreaterThanSignEqualsSignKeyword_1_0_0_1 = (Keyword)cGroup_1_0_0.eContents().get(1);
		private final Group cGroup_1_0_1 = (Group)cAlternatives_1_0.eContents().get(1);
		private final Action cLessEqLeftAction_1_0_1_0 = (Action)cGroup_1_0_1.eContents().get(0);
		private final Keyword cLessThanSignEqualsSignKeyword_1_0_1_1 = (Keyword)cGroup_1_0_1.eContents().get(1);
		private final Group cGroup_1_0_2 = (Group)cAlternatives_1_0.eContents().get(2);
		private final Action cGreaterLeftAction_1_0_2_0 = (Action)cGroup_1_0_2.eContents().get(0);
		private final Keyword cGreaterThanSignKeyword_1_0_2_1 = (Keyword)cGroup_1_0_2.eContents().get(1);
		private final Group cGroup_1_0_3 = (Group)cAlternatives_1_0.eContents().get(3);
		private final Action cLessLeftAction_1_0_3_0 = (Action)cGroup_1_0_3.eContents().get(0);
		private final Keyword cLessThanSignKeyword_1_0_3_1 = (Keyword)cGroup_1_0_3.eContents().get(1);
		private final Assignment cRightAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cRightPlusOrMinusParserRuleCall_1_1_0 = (RuleCall)cRightAssignment_1_1.eContents().get(0);
		
		//Comparison returns Expression:
		//    PlusOrMinus (
		//        (
		//            {GreaterEq.left=current} ">=" |
		//            {LessEq.left=current} "<=" |
		//            {Greater.left=current} '>' |
		//            {Less.left=current} "<"
		//        )
		//        right=PlusOrMinus
		//    )*;
		@Override public ParserRule getRule() { return rule; }
		
		//PlusOrMinus (
		//    (
		//        {GreaterEq.left=current} ">=" |
		//        {LessEq.left=current} "<=" |
		//        {Greater.left=current} '>' |
		//        {Less.left=current} "<"
		//    )
		//    right=PlusOrMinus
		//)*
		public Group getGroup() { return cGroup; }
		
		//PlusOrMinus
		public RuleCall getPlusOrMinusParserRuleCall_0() { return cPlusOrMinusParserRuleCall_0; }
		
		//(
		//       (
		//           {GreaterEq.left=current} ">=" |
		//           {LessEq.left=current} "<=" |
		//           {Greater.left=current} '>' |
		//           {Less.left=current} "<"
		//       )
		//       right=PlusOrMinus
		//   )*
		public Group getGroup_1() { return cGroup_1; }
		
		//(
		//    {GreaterEq.left=current} ">=" |
		//    {LessEq.left=current} "<=" |
		//    {Greater.left=current} '>' |
		//    {Less.left=current} "<"
		//)
		public Alternatives getAlternatives_1_0() { return cAlternatives_1_0; }
		
		//{GreaterEq.left=current} ">="
		public Group getGroup_1_0_0() { return cGroup_1_0_0; }
		
		//{GreaterEq.left=current}
		public Action getGreaterEqLeftAction_1_0_0_0() { return cGreaterEqLeftAction_1_0_0_0; }
		
		//">="
		public Keyword getGreaterThanSignEqualsSignKeyword_1_0_0_1() { return cGreaterThanSignEqualsSignKeyword_1_0_0_1; }
		
		//{LessEq.left=current} "<="
		public Group getGroup_1_0_1() { return cGroup_1_0_1; }
		
		//{LessEq.left=current}
		public Action getLessEqLeftAction_1_0_1_0() { return cLessEqLeftAction_1_0_1_0; }
		
		//"<="
		public Keyword getLessThanSignEqualsSignKeyword_1_0_1_1() { return cLessThanSignEqualsSignKeyword_1_0_1_1; }
		
		//{Greater.left=current} '>'
		public Group getGroup_1_0_2() { return cGroup_1_0_2; }
		
		//{Greater.left=current}
		public Action getGreaterLeftAction_1_0_2_0() { return cGreaterLeftAction_1_0_2_0; }
		
		//'>'
		public Keyword getGreaterThanSignKeyword_1_0_2_1() { return cGreaterThanSignKeyword_1_0_2_1; }
		
		//{Less.left=current} "<"
		public Group getGroup_1_0_3() { return cGroup_1_0_3; }
		
		//{Less.left=current}
		public Action getLessLeftAction_1_0_3_0() { return cLessLeftAction_1_0_3_0; }
		
		//"<"
		public Keyword getLessThanSignKeyword_1_0_3_1() { return cLessThanSignKeyword_1_0_3_1; }
		
		//right=PlusOrMinus
		public Assignment getRightAssignment_1_1() { return cRightAssignment_1_1; }
		
		//PlusOrMinus
		public RuleCall getRightPlusOrMinusParserRuleCall_1_1_0() { return cRightPlusOrMinusParserRuleCall_1_1_0; }
	}
	public class PlusOrMinusElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "lu.list.swrdi.formulaKPI.KPIFormulaDSL.PlusOrMinus");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cMulOrDivParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Alternatives cAlternatives_1_0 = (Alternatives)cGroup_1.eContents().get(0);
		private final Group cGroup_1_0_0 = (Group)cAlternatives_1_0.eContents().get(0);
		private final Action cPlusLeftAction_1_0_0_0 = (Action)cGroup_1_0_0.eContents().get(0);
		private final Keyword cPlusSignKeyword_1_0_0_1 = (Keyword)cGroup_1_0_0.eContents().get(1);
		private final Group cGroup_1_0_1 = (Group)cAlternatives_1_0.eContents().get(1);
		private final Action cMinusLeftAction_1_0_1_0 = (Action)cGroup_1_0_1.eContents().get(0);
		private final Keyword cHyphenMinusKeyword_1_0_1_1 = (Keyword)cGroup_1_0_1.eContents().get(1);
		private final Assignment cRightAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cRightMulOrDivParserRuleCall_1_1_0 = (RuleCall)cRightAssignment_1_1.eContents().get(0);
		
		//PlusOrMinus returns Expression:
		//    MulOrDiv (
		//        ({Plus.left=current} '+' | {Minus.left=current} '-')
		//        right=MulOrDiv
		//    )*;
		@Override public ParserRule getRule() { return rule; }
		
		//MulOrDiv (
		//    ({Plus.left=current} '+' | {Minus.left=current} '-')
		//    right=MulOrDiv
		//)*
		public Group getGroup() { return cGroup; }
		
		//MulOrDiv
		public RuleCall getMulOrDivParserRuleCall_0() { return cMulOrDivParserRuleCall_0; }
		
		//(
		//       ({Plus.left=current} '+' | {Minus.left=current} '-')
		//       right=MulOrDiv
		//   )*
		public Group getGroup_1() { return cGroup_1; }
		
		//({Plus.left=current} '+' | {Minus.left=current} '-')
		public Alternatives getAlternatives_1_0() { return cAlternatives_1_0; }
		
		//{Plus.left=current} '+'
		public Group getGroup_1_0_0() { return cGroup_1_0_0; }
		
		//{Plus.left=current}
		public Action getPlusLeftAction_1_0_0_0() { return cPlusLeftAction_1_0_0_0; }
		
		//'+'
		public Keyword getPlusSignKeyword_1_0_0_1() { return cPlusSignKeyword_1_0_0_1; }
		
		//{Minus.left=current} '-'
		public Group getGroup_1_0_1() { return cGroup_1_0_1; }
		
		//{Minus.left=current}
		public Action getMinusLeftAction_1_0_1_0() { return cMinusLeftAction_1_0_1_0; }
		
		//'-'
		public Keyword getHyphenMinusKeyword_1_0_1_1() { return cHyphenMinusKeyword_1_0_1_1; }
		
		//right=MulOrDiv
		public Assignment getRightAssignment_1_1() { return cRightAssignment_1_1; }
		
		//MulOrDiv
		public RuleCall getRightMulOrDivParserRuleCall_1_1_0() { return cRightMulOrDivParserRuleCall_1_1_0; }
	}
	public class MulOrDivElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "lu.list.swrdi.formulaKPI.KPIFormulaDSL.MulOrDiv");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cPrimaryParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Alternatives cAlternatives_1_0 = (Alternatives)cGroup_1.eContents().get(0);
		private final Group cGroup_1_0_0 = (Group)cAlternatives_1_0.eContents().get(0);
		private final Action cMultiplyLeftAction_1_0_0_0 = (Action)cGroup_1_0_0.eContents().get(0);
		private final Keyword cAsteriskKeyword_1_0_0_1 = (Keyword)cGroup_1_0_0.eContents().get(1);
		private final Group cGroup_1_0_1 = (Group)cAlternatives_1_0.eContents().get(1);
		private final Action cDivideLeftAction_1_0_1_0 = (Action)cGroup_1_0_1.eContents().get(0);
		private final Keyword cSolidusKeyword_1_0_1_1 = (Keyword)cGroup_1_0_1.eContents().get(1);
		private final Assignment cRightAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cRightPrimaryParserRuleCall_1_1_0 = (RuleCall)cRightAssignment_1_1.eContents().get(0);
		
		//MulOrDiv returns Expression:
		//    Primary (
		//        ({Multiply.left=current} '*' | {Divide.left=current} '/')
		//        right=Primary
		//    )*;
		@Override public ParserRule getRule() { return rule; }
		
		//Primary (
		//    ({Multiply.left=current} '*' | {Divide.left=current} '/')
		//    right=Primary
		//)*
		public Group getGroup() { return cGroup; }
		
		//Primary
		public RuleCall getPrimaryParserRuleCall_0() { return cPrimaryParserRuleCall_0; }
		
		//(
		//       ({Multiply.left=current} '*' | {Divide.left=current} '/')
		//       right=Primary
		//   )*
		public Group getGroup_1() { return cGroup_1; }
		
		//({Multiply.left=current} '*' | {Divide.left=current} '/')
		public Alternatives getAlternatives_1_0() { return cAlternatives_1_0; }
		
		//{Multiply.left=current} '*'
		public Group getGroup_1_0_0() { return cGroup_1_0_0; }
		
		//{Multiply.left=current}
		public Action getMultiplyLeftAction_1_0_0_0() { return cMultiplyLeftAction_1_0_0_0; }
		
		//'*'
		public Keyword getAsteriskKeyword_1_0_0_1() { return cAsteriskKeyword_1_0_0_1; }
		
		//{Divide.left=current} '/'
		public Group getGroup_1_0_1() { return cGroup_1_0_1; }
		
		//{Divide.left=current}
		public Action getDivideLeftAction_1_0_1_0() { return cDivideLeftAction_1_0_1_0; }
		
		//'/'
		public Keyword getSolidusKeyword_1_0_1_1() { return cSolidusKeyword_1_0_1_1; }
		
		//right=Primary
		public Assignment getRightAssignment_1_1() { return cRightAssignment_1_1; }
		
		//Primary
		public RuleCall getRightPrimaryParserRuleCall_1_1_0() { return cRightPrimaryParserRuleCall_1_1_0; }
	}
	public class PrimaryElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "lu.list.swrdi.formulaKPI.KPIFormulaDSL.Primary");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final RuleCall cExpressionParserRuleCall_0_1 = (RuleCall)cGroup_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_0_2 = (Keyword)cGroup_0.eContents().get(2);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Action cNotAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Keyword cExclamationMarkKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final Assignment cExpressionAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cExpressionPrimaryParserRuleCall_1_2_0 = (RuleCall)cExpressionAssignment_1_2.eContents().get(0);
		private final Group cGroup_2 = (Group)cAlternatives.eContents().get(2);
		private final Action cUnaryMinusAction_2_0 = (Action)cGroup_2.eContents().get(0);
		private final Keyword cHyphenMinusKeyword_2_1 = (Keyword)cGroup_2.eContents().get(1);
		private final Assignment cExpressionAssignment_2_2 = (Assignment)cGroup_2.eContents().get(2);
		private final RuleCall cExpressionPrimaryParserRuleCall_2_2_0 = (RuleCall)cExpressionAssignment_2_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cAlternatives.eContents().get(3);
		private final Action cAvgOpAction_3_0 = (Action)cGroup_3.eContents().get(0);
		private final Keyword cAVERAGEKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_3_2 = (Keyword)cGroup_3.eContents().get(2);
		private final Assignment cExpressionsAssignment_3_3 = (Assignment)cGroup_3.eContents().get(3);
		private final RuleCall cExpressionsExpressionParserRuleCall_3_3_0 = (RuleCall)cExpressionsAssignment_3_3.eContents().get(0);
		private final Group cGroup_3_4 = (Group)cGroup_3.eContents().get(4);
		private final Keyword cCommaKeyword_3_4_0 = (Keyword)cGroup_3_4.eContents().get(0);
		private final Assignment cExpressionsAssignment_3_4_1 = (Assignment)cGroup_3_4.eContents().get(1);
		private final RuleCall cExpressionsExpressionParserRuleCall_3_4_1_0 = (RuleCall)cExpressionsAssignment_3_4_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_3_5 = (Keyword)cGroup_3.eContents().get(5);
		private final Group cGroup_4 = (Group)cAlternatives.eContents().get(4);
		private final Action cWeightedSumOpAction_4_0 = (Action)cGroup_4.eContents().get(0);
		private final Keyword cWEIGHTED_SUMKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_4_2 = (Keyword)cGroup_4.eContents().get(2);
		private final Assignment cExpressionsAssignment_4_3 = (Assignment)cGroup_4.eContents().get(3);
		private final RuleCall cExpressionsExpressionParserRuleCall_4_3_0 = (RuleCall)cExpressionsAssignment_4_3.eContents().get(0);
		private final Keyword cColonKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Assignment cWeightsAssignment_4_5 = (Assignment)cGroup_4.eContents().get(5);
		private final RuleCall cWeightsExpressionParserRuleCall_4_5_0 = (RuleCall)cWeightsAssignment_4_5.eContents().get(0);
		private final Group cGroup_4_6 = (Group)cGroup_4.eContents().get(6);
		private final Keyword cCommaKeyword_4_6_0 = (Keyword)cGroup_4_6.eContents().get(0);
		private final Assignment cExpressionsAssignment_4_6_1 = (Assignment)cGroup_4_6.eContents().get(1);
		private final RuleCall cExpressionsExpressionParserRuleCall_4_6_1_0 = (RuleCall)cExpressionsAssignment_4_6_1.eContents().get(0);
		private final Keyword cColonKeyword_4_6_2 = (Keyword)cGroup_4_6.eContents().get(2);
		private final Assignment cWeightsAssignment_4_6_3 = (Assignment)cGroup_4_6.eContents().get(3);
		private final RuleCall cWeightsExpressionParserRuleCall_4_6_3_0 = (RuleCall)cWeightsAssignment_4_6_3.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_4_7 = (Keyword)cGroup_4.eContents().get(7);
		private final Group cGroup_5 = (Group)cAlternatives.eContents().get(5);
		private final Action cMinOpAction_5_0 = (Action)cGroup_5.eContents().get(0);
		private final Keyword cMINKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_5_2 = (Keyword)cGroup_5.eContents().get(2);
		private final Assignment cExpressionsAssignment_5_3 = (Assignment)cGroup_5.eContents().get(3);
		private final RuleCall cExpressionsExpressionParserRuleCall_5_3_0 = (RuleCall)cExpressionsAssignment_5_3.eContents().get(0);
		private final Group cGroup_5_4 = (Group)cGroup_5.eContents().get(4);
		private final Keyword cCommaKeyword_5_4_0 = (Keyword)cGroup_5_4.eContents().get(0);
		private final Assignment cExpressionsAssignment_5_4_1 = (Assignment)cGroup_5_4.eContents().get(1);
		private final RuleCall cExpressionsExpressionParserRuleCall_5_4_1_0 = (RuleCall)cExpressionsAssignment_5_4_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_5_5 = (Keyword)cGroup_5.eContents().get(5);
		private final Group cGroup_6 = (Group)cAlternatives.eContents().get(6);
		private final Action cMaxOpAction_6_0 = (Action)cGroup_6.eContents().get(0);
		private final Keyword cMAXKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_6_2 = (Keyword)cGroup_6.eContents().get(2);
		private final Assignment cExpressionsAssignment_6_3 = (Assignment)cGroup_6.eContents().get(3);
		private final RuleCall cExpressionsExpressionParserRuleCall_6_3_0 = (RuleCall)cExpressionsAssignment_6_3.eContents().get(0);
		private final Group cGroup_6_4 = (Group)cGroup_6.eContents().get(4);
		private final Keyword cCommaKeyword_6_4_0 = (Keyword)cGroup_6_4.eContents().get(0);
		private final Assignment cExpressionsAssignment_6_4_1 = (Assignment)cGroup_6_4.eContents().get(1);
		private final RuleCall cExpressionsExpressionParserRuleCall_6_4_1_0 = (RuleCall)cExpressionsAssignment_6_4_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_6_5 = (Keyword)cGroup_6.eContents().get(5);
		private final Group cGroup_7 = (Group)cAlternatives.eContents().get(7);
		private final Action cThresholdOpAction_7_0 = (Action)cGroup_7.eContents().get(0);
		private final Keyword cTHRESHOLDKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_7_2 = (Keyword)cGroup_7.eContents().get(2);
		private final Assignment cExpressionAssignment_7_3 = (Assignment)cGroup_7.eContents().get(3);
		private final RuleCall cExpressionExpressionParserRuleCall_7_3_0 = (RuleCall)cExpressionAssignment_7_3.eContents().get(0);
		private final Keyword cCommaKeyword_7_4 = (Keyword)cGroup_7.eContents().get(4);
		private final Assignment cThresholdAssignment_7_5 = (Assignment)cGroup_7.eContents().get(5);
		private final RuleCall cThresholdExpressionParserRuleCall_7_5_0 = (RuleCall)cThresholdAssignment_7_5.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_7_6 = (Keyword)cGroup_7.eContents().get(6);
		private final RuleCall cAtomicParserRuleCall_8 = (RuleCall)cAlternatives.eContents().get(8);
		
		//Primary returns Expression:
		//    '(' Expression ')' |
		//    {Not} "!" expression=Primary |
		//    {UnaryMinus} "-" expression=Primary |
		//    {AvgOp} "AVERAGE" "(" expressions+=Expression ("," expressions+=Expression)* ")" |
		//    {WeightedSumOp} "WEIGHTED_SUM" "(" expressions+=Expression ":" weights+=Expression ("," expressions+=Expression ":" weights+=Expression)* ")" |
		//    {MinOp} "MIN" "(" expressions+=Expression ("," expressions+=Expression)* ")" |
		//    {MaxOp} "MAX" "(" expressions+=Expression ("," expressions+=Expression)* ")" |
		//    {ThresholdOp} "THRESHOLD" "(" expression=Expression "," threshold=Expression ")" |
		//    Atomic;
		@Override public ParserRule getRule() { return rule; }
		
		//'(' Expression ')' |
		//{Not} "!" expression=Primary |
		//{UnaryMinus} "-" expression=Primary |
		//{AvgOp} "AVERAGE" "(" expressions+=Expression ("," expressions+=Expression)* ")" |
		//{WeightedSumOp} "WEIGHTED_SUM" "(" expressions+=Expression ":" weights+=Expression ("," expressions+=Expression ":" weights+=Expression)* ")" |
		//{MinOp} "MIN" "(" expressions+=Expression ("," expressions+=Expression)* ")" |
		//{MaxOp} "MAX" "(" expressions+=Expression ("," expressions+=Expression)* ")" |
		//{ThresholdOp} "THRESHOLD" "(" expression=Expression "," threshold=Expression ")" |
		//Atomic
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'(' Expression ')'
		public Group getGroup_0() { return cGroup_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_0_0() { return cLeftParenthesisKeyword_0_0; }
		
		//Expression
		public RuleCall getExpressionParserRuleCall_0_1() { return cExpressionParserRuleCall_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_0_2() { return cRightParenthesisKeyword_0_2; }
		
		//{Not} "!" expression=Primary
		public Group getGroup_1() { return cGroup_1; }
		
		//{Not}
		public Action getNotAction_1_0() { return cNotAction_1_0; }
		
		//"!"
		public Keyword getExclamationMarkKeyword_1_1() { return cExclamationMarkKeyword_1_1; }
		
		//expression=Primary
		public Assignment getExpressionAssignment_1_2() { return cExpressionAssignment_1_2; }
		
		//Primary
		public RuleCall getExpressionPrimaryParserRuleCall_1_2_0() { return cExpressionPrimaryParserRuleCall_1_2_0; }
		
		//{UnaryMinus} "-" expression=Primary
		public Group getGroup_2() { return cGroup_2; }
		
		//{UnaryMinus}
		public Action getUnaryMinusAction_2_0() { return cUnaryMinusAction_2_0; }
		
		//"-"
		public Keyword getHyphenMinusKeyword_2_1() { return cHyphenMinusKeyword_2_1; }
		
		//expression=Primary
		public Assignment getExpressionAssignment_2_2() { return cExpressionAssignment_2_2; }
		
		//Primary
		public RuleCall getExpressionPrimaryParserRuleCall_2_2_0() { return cExpressionPrimaryParserRuleCall_2_2_0; }
		
		//{AvgOp} "AVERAGE" "(" expressions+=Expression ("," expressions+=Expression)* ")"
		public Group getGroup_3() { return cGroup_3; }
		
		//{AvgOp}
		public Action getAvgOpAction_3_0() { return cAvgOpAction_3_0; }
		
		//"AVERAGE"
		public Keyword getAVERAGEKeyword_3_1() { return cAVERAGEKeyword_3_1; }
		
		//"("
		public Keyword getLeftParenthesisKeyword_3_2() { return cLeftParenthesisKeyword_3_2; }
		
		//expressions+=Expression
		public Assignment getExpressionsAssignment_3_3() { return cExpressionsAssignment_3_3; }
		
		//Expression
		public RuleCall getExpressionsExpressionParserRuleCall_3_3_0() { return cExpressionsExpressionParserRuleCall_3_3_0; }
		
		//("," expressions+=Expression)*
		public Group getGroup_3_4() { return cGroup_3_4; }
		
		//","
		public Keyword getCommaKeyword_3_4_0() { return cCommaKeyword_3_4_0; }
		
		//expressions+=Expression
		public Assignment getExpressionsAssignment_3_4_1() { return cExpressionsAssignment_3_4_1; }
		
		//Expression
		public RuleCall getExpressionsExpressionParserRuleCall_3_4_1_0() { return cExpressionsExpressionParserRuleCall_3_4_1_0; }
		
		//")"
		public Keyword getRightParenthesisKeyword_3_5() { return cRightParenthesisKeyword_3_5; }
		
		//{WeightedSumOp} "WEIGHTED_SUM" "(" expressions+=Expression ":" weights+=Expression ("," expressions+=Expression ":" weights+=Expression)* ")"
		public Group getGroup_4() { return cGroup_4; }
		
		//{WeightedSumOp}
		public Action getWeightedSumOpAction_4_0() { return cWeightedSumOpAction_4_0; }
		
		//"WEIGHTED_SUM"
		public Keyword getWEIGHTED_SUMKeyword_4_1() { return cWEIGHTED_SUMKeyword_4_1; }
		
		//"("
		public Keyword getLeftParenthesisKeyword_4_2() { return cLeftParenthesisKeyword_4_2; }
		
		//expressions+=Expression
		public Assignment getExpressionsAssignment_4_3() { return cExpressionsAssignment_4_3; }
		
		//Expression
		public RuleCall getExpressionsExpressionParserRuleCall_4_3_0() { return cExpressionsExpressionParserRuleCall_4_3_0; }
		
		//":"
		public Keyword getColonKeyword_4_4() { return cColonKeyword_4_4; }
		
		//weights+=Expression
		public Assignment getWeightsAssignment_4_5() { return cWeightsAssignment_4_5; }
		
		//Expression
		public RuleCall getWeightsExpressionParserRuleCall_4_5_0() { return cWeightsExpressionParserRuleCall_4_5_0; }
		
		//("," expressions+=Expression ":" weights+=Expression)*
		public Group getGroup_4_6() { return cGroup_4_6; }
		
		//","
		public Keyword getCommaKeyword_4_6_0() { return cCommaKeyword_4_6_0; }
		
		//expressions+=Expression
		public Assignment getExpressionsAssignment_4_6_1() { return cExpressionsAssignment_4_6_1; }
		
		//Expression
		public RuleCall getExpressionsExpressionParserRuleCall_4_6_1_0() { return cExpressionsExpressionParserRuleCall_4_6_1_0; }
		
		//":"
		public Keyword getColonKeyword_4_6_2() { return cColonKeyword_4_6_2; }
		
		//weights+=Expression
		public Assignment getWeightsAssignment_4_6_3() { return cWeightsAssignment_4_6_3; }
		
		//Expression
		public RuleCall getWeightsExpressionParserRuleCall_4_6_3_0() { return cWeightsExpressionParserRuleCall_4_6_3_0; }
		
		//")"
		public Keyword getRightParenthesisKeyword_4_7() { return cRightParenthesisKeyword_4_7; }
		
		//{MinOp} "MIN" "(" expressions+=Expression ("," expressions+=Expression)* ")"
		public Group getGroup_5() { return cGroup_5; }
		
		//{MinOp}
		public Action getMinOpAction_5_0() { return cMinOpAction_5_0; }
		
		//"MIN"
		public Keyword getMINKeyword_5_1() { return cMINKeyword_5_1; }
		
		//"("
		public Keyword getLeftParenthesisKeyword_5_2() { return cLeftParenthesisKeyword_5_2; }
		
		//expressions+=Expression
		public Assignment getExpressionsAssignment_5_3() { return cExpressionsAssignment_5_3; }
		
		//Expression
		public RuleCall getExpressionsExpressionParserRuleCall_5_3_0() { return cExpressionsExpressionParserRuleCall_5_3_0; }
		
		//("," expressions+=Expression)*
		public Group getGroup_5_4() { return cGroup_5_4; }
		
		//","
		public Keyword getCommaKeyword_5_4_0() { return cCommaKeyword_5_4_0; }
		
		//expressions+=Expression
		public Assignment getExpressionsAssignment_5_4_1() { return cExpressionsAssignment_5_4_1; }
		
		//Expression
		public RuleCall getExpressionsExpressionParserRuleCall_5_4_1_0() { return cExpressionsExpressionParserRuleCall_5_4_1_0; }
		
		//")"
		public Keyword getRightParenthesisKeyword_5_5() { return cRightParenthesisKeyword_5_5; }
		
		//{MaxOp} "MAX" "(" expressions+=Expression ("," expressions+=Expression)* ")"
		public Group getGroup_6() { return cGroup_6; }
		
		//{MaxOp}
		public Action getMaxOpAction_6_0() { return cMaxOpAction_6_0; }
		
		//"MAX"
		public Keyword getMAXKeyword_6_1() { return cMAXKeyword_6_1; }
		
		//"("
		public Keyword getLeftParenthesisKeyword_6_2() { return cLeftParenthesisKeyword_6_2; }
		
		//expressions+=Expression
		public Assignment getExpressionsAssignment_6_3() { return cExpressionsAssignment_6_3; }
		
		//Expression
		public RuleCall getExpressionsExpressionParserRuleCall_6_3_0() { return cExpressionsExpressionParserRuleCall_6_3_0; }
		
		//("," expressions+=Expression)*
		public Group getGroup_6_4() { return cGroup_6_4; }
		
		//","
		public Keyword getCommaKeyword_6_4_0() { return cCommaKeyword_6_4_0; }
		
		//expressions+=Expression
		public Assignment getExpressionsAssignment_6_4_1() { return cExpressionsAssignment_6_4_1; }
		
		//Expression
		public RuleCall getExpressionsExpressionParserRuleCall_6_4_1_0() { return cExpressionsExpressionParserRuleCall_6_4_1_0; }
		
		//")"
		public Keyword getRightParenthesisKeyword_6_5() { return cRightParenthesisKeyword_6_5; }
		
		//{ThresholdOp} "THRESHOLD" "(" expression=Expression "," threshold=Expression ")"
		public Group getGroup_7() { return cGroup_7; }
		
		//{ThresholdOp}
		public Action getThresholdOpAction_7_0() { return cThresholdOpAction_7_0; }
		
		//"THRESHOLD"
		public Keyword getTHRESHOLDKeyword_7_1() { return cTHRESHOLDKeyword_7_1; }
		
		//"("
		public Keyword getLeftParenthesisKeyword_7_2() { return cLeftParenthesisKeyword_7_2; }
		
		//expression=Expression
		public Assignment getExpressionAssignment_7_3() { return cExpressionAssignment_7_3; }
		
		//Expression
		public RuleCall getExpressionExpressionParserRuleCall_7_3_0() { return cExpressionExpressionParserRuleCall_7_3_0; }
		
		//","
		public Keyword getCommaKeyword_7_4() { return cCommaKeyword_7_4; }
		
		//threshold=Expression
		public Assignment getThresholdAssignment_7_5() { return cThresholdAssignment_7_5; }
		
		//Expression
		public RuleCall getThresholdExpressionParserRuleCall_7_5_0() { return cThresholdExpressionParserRuleCall_7_5_0; }
		
		//")"
		public Keyword getRightParenthesisKeyword_7_6() { return cRightParenthesisKeyword_7_6; }
		
		//Atomic
		public RuleCall getAtomicParserRuleCall_8() { return cAtomicParserRuleCall_8; }
	}
	public class AtomicElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "lu.list.swrdi.formulaKPI.KPIFormulaDSL.Atomic");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Action cIntConstantAction_0_0 = (Action)cGroup_0.eContents().get(0);
		private final Assignment cValueAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final RuleCall cValueINTTerminalRuleCall_0_1_0 = (RuleCall)cValueAssignment_0_1.eContents().get(0);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Action cRealConstantAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Assignment cValueAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cValueDOUBLETerminalRuleCall_1_1_0 = (RuleCall)cValueAssignment_1_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cAlternatives.eContents().get(2);
		private final Action cTextConstantAction_2_0 = (Action)cGroup_2.eContents().get(0);
		private final Assignment cValueAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cValueSTRINGTerminalRuleCall_2_1_0 = (RuleCall)cValueAssignment_2_1.eContents().get(0);
		private final Group cGroup_3 = (Group)cAlternatives.eContents().get(3);
		private final Action cBoolConstantAction_3_0 = (Action)cGroup_3.eContents().get(0);
		private final Assignment cValueAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final Alternatives cValueAlternatives_3_1_0 = (Alternatives)cValueAssignment_3_1.eContents().get(0);
		private final Keyword cValueTrueKeyword_3_1_0_0 = (Keyword)cValueAlternatives_3_1_0.eContents().get(0);
		private final Keyword cValueFalseKeyword_3_1_0_1 = (Keyword)cValueAlternatives_3_1_0.eContents().get(1);
		private final Group cGroup_4 = (Group)cAlternatives.eContents().get(4);
		private final Action cUnitConstantAction_4_0 = (Action)cGroup_4.eContents().get(0);
		private final Assignment cValueAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cValueDOUBLETerminalRuleCall_4_1_0 = (RuleCall)cValueAssignment_4_1.eContents().get(0);
		private final Assignment cUnitAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cUnitValueUnitEnumRuleCall_4_2_0 = (RuleCall)cUnitAssignment_4_2.eContents().get(0);
		private final Group cGroup_5 = (Group)cAlternatives.eContents().get(5);
		private final Action cEnumLiteralRefAction_5_0 = (Action)cGroup_5.eContents().get(0);
		private final Assignment cLiteralAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final CrossReference cLiteralEnumerationLiteralCrossReference_5_1_0 = (CrossReference)cLiteralAssignment_5_1.eContents().get(0);
		private final RuleCall cLiteralEnumerationLiteralFQNTerminalRuleCall_5_1_0_1 = (RuleCall)cLiteralEnumerationLiteralCrossReference_5_1_0.eContents().get(1);
		private final Group cGroup_6 = (Group)cAlternatives.eContents().get(6);
		private final Action cComputableRefAction_6_0 = (Action)cGroup_6.eContents().get(0);
		private final Assignment cComputableAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final CrossReference cComputableComputableCrossReference_6_1_0 = (CrossReference)cComputableAssignment_6_1.eContents().get(0);
		private final RuleCall cComputableComputableIDTerminalRuleCall_6_1_0_1 = (RuleCall)cComputableComputableCrossReference_6_1_0.eContents().get(1);
		
		//Atomic returns Expression:
		//    {IntConstant} value=INT |
		//    {RealConstant} value=DOUBLE |
		//    {TextConstant} value=STRING |
		//    {BoolConstant} value=('true' | 'false') |
		//    {UnitConstant} value=DOUBLE unit=ValueUnit |
		//    {EnumLiteralRef} literal=[EnumerationLiteral|FQN] |
		//    {ComputableRef} computable=[Computable]
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//{IntConstant} value=INT |
		//{RealConstant} value=DOUBLE |
		//{TextConstant} value=STRING |
		//{BoolConstant} value=('true' | 'false') |
		//{UnitConstant} value=DOUBLE unit=ValueUnit |
		//{EnumLiteralRef} literal=[EnumerationLiteral|FQN] |
		//{ComputableRef} computable=[Computable]
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//{IntConstant} value=INT
		public Group getGroup_0() { return cGroup_0; }
		
		//{IntConstant}
		public Action getIntConstantAction_0_0() { return cIntConstantAction_0_0; }
		
		//value=INT
		public Assignment getValueAssignment_0_1() { return cValueAssignment_0_1; }
		
		//INT
		public RuleCall getValueINTTerminalRuleCall_0_1_0() { return cValueINTTerminalRuleCall_0_1_0; }
		
		//{RealConstant} value=DOUBLE
		public Group getGroup_1() { return cGroup_1; }
		
		//{RealConstant}
		public Action getRealConstantAction_1_0() { return cRealConstantAction_1_0; }
		
		//value=DOUBLE
		public Assignment getValueAssignment_1_1() { return cValueAssignment_1_1; }
		
		//DOUBLE
		public RuleCall getValueDOUBLETerminalRuleCall_1_1_0() { return cValueDOUBLETerminalRuleCall_1_1_0; }
		
		//{TextConstant} value=STRING
		public Group getGroup_2() { return cGroup_2; }
		
		//{TextConstant}
		public Action getTextConstantAction_2_0() { return cTextConstantAction_2_0; }
		
		//value=STRING
		public Assignment getValueAssignment_2_1() { return cValueAssignment_2_1; }
		
		//STRING
		public RuleCall getValueSTRINGTerminalRuleCall_2_1_0() { return cValueSTRINGTerminalRuleCall_2_1_0; }
		
		//{BoolConstant} value=('true' | 'false')
		public Group getGroup_3() { return cGroup_3; }
		
		//{BoolConstant}
		public Action getBoolConstantAction_3_0() { return cBoolConstantAction_3_0; }
		
		//value=('true' | 'false')
		public Assignment getValueAssignment_3_1() { return cValueAssignment_3_1; }
		
		//('true' | 'false')
		public Alternatives getValueAlternatives_3_1_0() { return cValueAlternatives_3_1_0; }
		
		//'true'
		public Keyword getValueTrueKeyword_3_1_0_0() { return cValueTrueKeyword_3_1_0_0; }
		
		//'false'
		public Keyword getValueFalseKeyword_3_1_0_1() { return cValueFalseKeyword_3_1_0_1; }
		
		//{UnitConstant} value=DOUBLE unit=ValueUnit
		public Group getGroup_4() { return cGroup_4; }
		
		//{UnitConstant}
		public Action getUnitConstantAction_4_0() { return cUnitConstantAction_4_0; }
		
		//value=DOUBLE
		public Assignment getValueAssignment_4_1() { return cValueAssignment_4_1; }
		
		//DOUBLE
		public RuleCall getValueDOUBLETerminalRuleCall_4_1_0() { return cValueDOUBLETerminalRuleCall_4_1_0; }
		
		//unit=ValueUnit
		public Assignment getUnitAssignment_4_2() { return cUnitAssignment_4_2; }
		
		//ValueUnit
		public RuleCall getUnitValueUnitEnumRuleCall_4_2_0() { return cUnitValueUnitEnumRuleCall_4_2_0; }
		
		//{EnumLiteralRef} literal=[EnumerationLiteral|FQN]
		public Group getGroup_5() { return cGroup_5; }
		
		//{EnumLiteralRef}
		public Action getEnumLiteralRefAction_5_0() { return cEnumLiteralRefAction_5_0; }
		
		//literal=[EnumerationLiteral|FQN]
		public Assignment getLiteralAssignment_5_1() { return cLiteralAssignment_5_1; }
		
		//[EnumerationLiteral|FQN]
		public CrossReference getLiteralEnumerationLiteralCrossReference_5_1_0() { return cLiteralEnumerationLiteralCrossReference_5_1_0; }
		
		//FQN
		public RuleCall getLiteralEnumerationLiteralFQNTerminalRuleCall_5_1_0_1() { return cLiteralEnumerationLiteralFQNTerminalRuleCall_5_1_0_1; }
		
		//{ComputableRef} computable=[Computable]
		public Group getGroup_6() { return cGroup_6; }
		
		//{ComputableRef}
		public Action getComputableRefAction_6_0() { return cComputableRefAction_6_0; }
		
		//computable=[Computable]
		public Assignment getComputableAssignment_6_1() { return cComputableAssignment_6_1; }
		
		//[Computable]
		public CrossReference getComputableComputableCrossReference_6_1_0() { return cComputableComputableCrossReference_6_1_0; }
		
		//ID
		public RuleCall getComputableComputableIDTerminalRuleCall_6_1_0_1() { return cComputableComputableIDTerminalRuleCall_6_1_0_1; }
	}
	
	public class WindowUnitElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "lu.list.swrdi.formulaKPI.KPIFormulaDSL.WindowUnit");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cSECEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cSECSecondsKeyword_0_0 = (Keyword)cSECEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cMINEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cMINMinutesKeyword_1_0 = (Keyword)cMINEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cHOUREnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cHOURHoursKeyword_2_0 = (Keyword)cHOUREnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cDAYEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cDAYDaysKeyword_3_0 = (Keyword)cDAYEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cMEASUREMENTEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cMEASUREMENTMeasurementsKeyword_4_0 = (Keyword)cMEASUREMENTEnumLiteralDeclaration_4.eContents().get(0);
		
		//enum WindowUnit:
		//    SEC="seconds" |
		//    MIN="minutes" |
		//    HOUR="hours" |
		//    DAY="days" |
		//    MEASUREMENT="measurements"
		//;
		public EnumRule getRule() { return rule; }
		
		//SEC="seconds" |
		//MIN="minutes" |
		//HOUR="hours" |
		//DAY="days" |
		//MEASUREMENT="measurements"
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//SEC="seconds"
		public EnumLiteralDeclaration getSECEnumLiteralDeclaration_0() { return cSECEnumLiteralDeclaration_0; }
		
		//"seconds"
		public Keyword getSECSecondsKeyword_0_0() { return cSECSecondsKeyword_0_0; }
		
		//MIN="minutes"
		public EnumLiteralDeclaration getMINEnumLiteralDeclaration_1() { return cMINEnumLiteralDeclaration_1; }
		
		//"minutes"
		public Keyword getMINMinutesKeyword_1_0() { return cMINMinutesKeyword_1_0; }
		
		//HOUR="hours"
		public EnumLiteralDeclaration getHOUREnumLiteralDeclaration_2() { return cHOUREnumLiteralDeclaration_2; }
		
		//"hours"
		public Keyword getHOURHoursKeyword_2_0() { return cHOURHoursKeyword_2_0; }
		
		//DAY="days"
		public EnumLiteralDeclaration getDAYEnumLiteralDeclaration_3() { return cDAYEnumLiteralDeclaration_3; }
		
		//"days"
		public Keyword getDAYDaysKeyword_3_0() { return cDAYDaysKeyword_3_0; }
		
		//MEASUREMENT="measurements"
		public EnumLiteralDeclaration getMEASUREMENTEnumLiteralDeclaration_4() { return cMEASUREMENTEnumLiteralDeclaration_4; }
		
		//"measurements"
		public Keyword getMEASUREMENTMeasurementsKeyword_4_0() { return cMEASUREMENTMeasurementsKeyword_4_0; }
	}
	public class ValueUnitElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "lu.list.swrdi.formulaKPI.KPIFormulaDSL.ValueUnit");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cMILLIEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cMILLIMillisecondsKeyword_0_0 = (Keyword)cMILLIEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cSECEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cSECSecondsKeyword_1_0 = (Keyword)cSECEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cMINEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cMINMinutesKeyword_2_0 = (Keyword)cMINEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cHOUREnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cHOURHoursKeyword_3_0 = (Keyword)cHOUREnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cLITERSEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cLITERSLitersKeyword_4_0 = (Keyword)cLITERSEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cM3EnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cM3CubicMeterKeyword_5_0 = (Keyword)cM3EnumLiteralDeclaration_5.eContents().get(0);
		private final EnumLiteralDeclaration cWhEnumLiteralDeclaration_6 = (EnumLiteralDeclaration)cAlternatives.eContents().get(6);
		private final Keyword cWhWhKeyword_6_0 = (Keyword)cWhEnumLiteralDeclaration_6.eContents().get(0);
		private final EnumLiteralDeclaration cKWhEnumLiteralDeclaration_7 = (EnumLiteralDeclaration)cAlternatives.eContents().get(7);
		private final Keyword cKWhKWhKeyword_7_0 = (Keyword)cKWhEnumLiteralDeclaration_7.eContents().get(0);
		private final EnumLiteralDeclaration cGCO2eqEnumLiteralDeclaration_8 = (EnumLiteralDeclaration)cAlternatives.eContents().get(8);
		private final Keyword cGCO2eqGCO2eqKeyword_8_0 = (Keyword)cGCO2eqEnumLiteralDeclaration_8.eContents().get(0);
		private final EnumLiteralDeclaration cKgCO2eqEnumLiteralDeclaration_9 = (EnumLiteralDeclaration)cAlternatives.eContents().get(9);
		private final Keyword cKgCO2eqKgCO2eqKeyword_9_0 = (Keyword)cKgCO2eqEnumLiteralDeclaration_9.eContents().get(0);
		
		//enum ValueUnit:
		//    MILLI="milliseconds" |
		//    SEC="seconds" |
		//    MIN="minutes" |
		//    HOUR="hours" |
		//    LITERS="liters" |
		//    M3="cubic meter" |
		//    Wh="Wh" |
		//    kWh="kWh" |
		//    gCO2eq="gCO2eq" |
		//    kgCO2eq="kgCO2eq"
		//;
		public EnumRule getRule() { return rule; }
		
		//MILLI="milliseconds" |
		//SEC="seconds" |
		//MIN="minutes" |
		//HOUR="hours" |
		//LITERS="liters" |
		//M3="cubic meter" |
		//Wh="Wh" |
		//kWh="kWh" |
		//gCO2eq="gCO2eq" |
		//kgCO2eq="kgCO2eq"
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//MILLI="milliseconds"
		public EnumLiteralDeclaration getMILLIEnumLiteralDeclaration_0() { return cMILLIEnumLiteralDeclaration_0; }
		
		//"milliseconds"
		public Keyword getMILLIMillisecondsKeyword_0_0() { return cMILLIMillisecondsKeyword_0_0; }
		
		//SEC="seconds"
		public EnumLiteralDeclaration getSECEnumLiteralDeclaration_1() { return cSECEnumLiteralDeclaration_1; }
		
		//"seconds"
		public Keyword getSECSecondsKeyword_1_0() { return cSECSecondsKeyword_1_0; }
		
		//MIN="minutes"
		public EnumLiteralDeclaration getMINEnumLiteralDeclaration_2() { return cMINEnumLiteralDeclaration_2; }
		
		//"minutes"
		public Keyword getMINMinutesKeyword_2_0() { return cMINMinutesKeyword_2_0; }
		
		//HOUR="hours"
		public EnumLiteralDeclaration getHOUREnumLiteralDeclaration_3() { return cHOUREnumLiteralDeclaration_3; }
		
		//"hours"
		public Keyword getHOURHoursKeyword_3_0() { return cHOURHoursKeyword_3_0; }
		
		//LITERS="liters"
		public EnumLiteralDeclaration getLITERSEnumLiteralDeclaration_4() { return cLITERSEnumLiteralDeclaration_4; }
		
		//"liters"
		public Keyword getLITERSLitersKeyword_4_0() { return cLITERSLitersKeyword_4_0; }
		
		//M3="cubic meter"
		public EnumLiteralDeclaration getM3EnumLiteralDeclaration_5() { return cM3EnumLiteralDeclaration_5; }
		
		//"cubic meter"
		public Keyword getM3CubicMeterKeyword_5_0() { return cM3CubicMeterKeyword_5_0; }
		
		//Wh="Wh"
		public EnumLiteralDeclaration getWhEnumLiteralDeclaration_6() { return cWhEnumLiteralDeclaration_6; }
		
		//"Wh"
		public Keyword getWhWhKeyword_6_0() { return cWhWhKeyword_6_0; }
		
		//kWh="kWh"
		public EnumLiteralDeclaration getKWhEnumLiteralDeclaration_7() { return cKWhEnumLiteralDeclaration_7; }
		
		//"kWh"
		public Keyword getKWhKWhKeyword_7_0() { return cKWhKWhKeyword_7_0; }
		
		//gCO2eq="gCO2eq"
		public EnumLiteralDeclaration getGCO2eqEnumLiteralDeclaration_8() { return cGCO2eqEnumLiteralDeclaration_8; }
		
		//"gCO2eq"
		public Keyword getGCO2eqGCO2eqKeyword_8_0() { return cGCO2eqGCO2eqKeyword_8_0; }
		
		//kgCO2eq="kgCO2eq"
		public EnumLiteralDeclaration getKgCO2eqEnumLiteralDeclaration_9() { return cKgCO2eqEnumLiteralDeclaration_9; }
		
		//"kgCO2eq"
		public Keyword getKgCO2eqKgCO2eqKeyword_9_0() { return cKgCO2eqKgCO2eqKeyword_9_0; }
	}
	
	private final KPIFormulaDSLElements pKPIFormulaDSL;
	private final DeclarationElements pDeclaration;
	private final ComputationElements pComputation;
	private final DeclarableElements pDeclarable;
	private final MetricElements pMetric;
	private final KPIElements pKPI;
	private final ValueTypeElements pValueType;
	private final IntegerValueElements pIntegerValue;
	private final RealValueElements pRealValue;
	private final TextualValueElements pTextualValue;
	private final BooleanValueElements pBooleanValue;
	private final EnumerationValueElements pEnumerationValue;
	private final EnumerationLiteralElements pEnumerationLiteral;
	private final UnitValueElements pUnitValue;
	private final AggregationValueElements pAggregationValue;
	private final DriftValueElements pDriftValue;
	private final OperationElements pOperation;
	private final MinimumElements pMinimum;
	private final MaximumElements pMaximum;
	private final AverageElements pAverage;
	private final MedianElements pMedian;
	private final StandardDeviationElements pStandardDeviation;
	private final WindowUnitElements eWindowUnit;
	private final ValueUnitElements eValueUnit;
	private final ConditionElements pCondition;
	private final ExpressionElements pExpression;
	private final OrElements pOr;
	private final AndElements pAnd;
	private final EqualityElements pEquality;
	private final ComparisonElements pComparison;
	private final PlusOrMinusElements pPlusOrMinus;
	private final MulOrDivElements pMulOrDiv;
	private final PrimaryElements pPrimary;
	private final AtomicElements pAtomic;
	private final TerminalRule tDOUBLE;
	private final TerminalRule tFQN;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public KPIFormulaDSLGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pKPIFormulaDSL = new KPIFormulaDSLElements();
		this.pDeclaration = new DeclarationElements();
		this.pComputation = new ComputationElements();
		this.pDeclarable = new DeclarableElements();
		this.pMetric = new MetricElements();
		this.pKPI = new KPIElements();
		this.pValueType = new ValueTypeElements();
		this.pIntegerValue = new IntegerValueElements();
		this.pRealValue = new RealValueElements();
		this.pTextualValue = new TextualValueElements();
		this.pBooleanValue = new BooleanValueElements();
		this.pEnumerationValue = new EnumerationValueElements();
		this.pEnumerationLiteral = new EnumerationLiteralElements();
		this.pUnitValue = new UnitValueElements();
		this.pAggregationValue = new AggregationValueElements();
		this.pDriftValue = new DriftValueElements();
		this.pOperation = new OperationElements();
		this.pMinimum = new MinimumElements();
		this.pMaximum = new MaximumElements();
		this.pAverage = new AverageElements();
		this.pMedian = new MedianElements();
		this.pStandardDeviation = new StandardDeviationElements();
		this.eWindowUnit = new WindowUnitElements();
		this.eValueUnit = new ValueUnitElements();
		this.pCondition = new ConditionElements();
		this.pExpression = new ExpressionElements();
		this.pOr = new OrElements();
		this.pAnd = new AndElements();
		this.pEquality = new EqualityElements();
		this.pComparison = new ComparisonElements();
		this.pPlusOrMinus = new PlusOrMinusElements();
		this.pMulOrDiv = new MulOrDivElements();
		this.pPrimary = new PrimaryElements();
		this.pAtomic = new AtomicElements();
		this.tDOUBLE = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "lu.list.swrdi.formulaKPI.KPIFormulaDSL.DOUBLE");
		this.tFQN = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "lu.list.swrdi.formulaKPI.KPIFormulaDSL.FQN");
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("lu.list.swrdi.formulaKPI.KPIFormulaDSL".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//KPIFormulaDSL returns KPIFormula: declarations+=Declaration+ computations+=Computation+;
	public KPIFormulaDSLElements getKPIFormulaDSLAccess() {
		return pKPIFormulaDSL;
	}
	
	public ParserRule getKPIFormulaDSLRule() {
		return getKPIFormulaDSLAccess().getRule();
	}
	
	//Declaration returns Declaration: declared=Declarable;
	public DeclarationElements getDeclarationAccess() {
		return pDeclaration;
	}
	
	public ParserRule getDeclarationRule() {
		return getDeclarationAccess().getRule();
	}
	
	//Computation returns Computation: computed=[Computable] "=" formula=(Expression|Condition);
	public ComputationElements getComputationAccess() {
		return pComputation;
	}
	
	public ParserRule getComputationRule() {
		return getComputationAccess().getRule();
	}
	
	//Declarable returns Declarable: KPI | Metric;
	public DeclarableElements getDeclarableAccess() {
		return pDeclarable;
	}
	
	public ParserRule getDeclarableRule() {
		return getDeclarableAccess().getRule();
	}
	
	//Metric returns Metric: name=ID "of" "type" type=ValueType;
	public MetricElements getMetricAccess() {
		return pMetric;
	}
	
	public ParserRule getMetricRule() {
		return getMetricAccess().getRule();
	}
	
	//KPI returns KPI: "KPI" name=ID "of" "type" type=ValueType;
	public KPIElements getKPIAccess() {
		return pKPI;
	}
	
	public ParserRule getKPIRule() {
		return getKPIAccess().getRule();
	}
	
	//ValueType returns ValueType:
	//    IntegerValue | RealValue | TextualValue | BooleanValue |
	//    EnumerationValue | AggregationValue | DriftValue | UnitValue
	//;
	public ValueTypeElements getValueTypeAccess() {
		return pValueType;
	}
	
	public ParserRule getValueTypeRule() {
		return getValueTypeAccess().getRule();
	}
	
	//IntegerValue : {IntegerValue} "int";
	public IntegerValueElements getIntegerValueAccess() {
		return pIntegerValue;
	}
	
	public ParserRule getIntegerValueRule() {
		return getIntegerValueAccess().getRule();
	}
	
	//RealValue: {RealValue} "real";
	public RealValueElements getRealValueAccess() {
		return pRealValue;
	}
	
	public ParserRule getRealValueRule() {
		return getRealValueAccess().getRule();
	}
	
	//TextualValue: {TextualValue} "text";
	public TextualValueElements getTextualValueAccess() {
		return pTextualValue;
	}
	
	public ParserRule getTextualValueRule() {
		return getTextualValueAccess().getRule();
	}
	
	//BooleanValue: {BooleanValue} "bool";
	public BooleanValueElements getBooleanValueAccess() {
		return pBooleanValue;
	}
	
	public ParserRule getBooleanValueRule() {
		return getBooleanValueAccess().getRule();
	}
	
	//EnumerationValue returns EnumerationValue: "{" literals+=EnumerationLiteral+ "}";
	public EnumerationValueElements getEnumerationValueAccess() {
		return pEnumerationValue;
	}
	
	public ParserRule getEnumerationValueRule() {
		return getEnumerationValueAccess().getRule();
	}
	
	//EnumerationLiteral returns EnumerationLiteral: name=ID;
	public EnumerationLiteralElements getEnumerationLiteralAccess() {
		return pEnumerationLiteral;
	}
	
	public ParserRule getEnumerationLiteralRule() {
		return getEnumerationLiteralAccess().getRule();
	}
	
	//UnitValue returns UnitValue: unit=ValueUnit;
	public UnitValueElements getUnitValueAccess() {
		return pUnitValue;
	}
	
	public ParserRule getUnitValueRule() {
		return getUnitValueAccess().getRule();
	}
	
	//AggregationValue returns AggregationValue: "aggregate" operation=Operation "for" window=INT windowUnit=WindowUnit;
	public AggregationValueElements getAggregationValueAccess() {
		return pAggregationValue;
	}
	
	public ParserRule getAggregationValueRule() {
		return getAggregationValueAccess().getRule();
	}
	
	//DriftValue returns DriftValue: "drift" "of" operation=Operation "for" window=INT windowUnit=WindowUnit;
	public DriftValueElements getDriftValueAccess() {
		return pDriftValue;
	}
	
	public ParserRule getDriftValueRule() {
		return getDriftValueAccess().getRule();
	}
	
	//Operation returns Operation:
	//    Minimum | Maximum | Average | Median | StandardDeviation
	//;
	public OperationElements getOperationAccess() {
		return pOperation;
	}
	
	public ParserRule getOperationRule() {
		return getOperationAccess().getRule();
	}
	
	//Minimum: {Minimum} "Minimum";
	public MinimumElements getMinimumAccess() {
		return pMinimum;
	}
	
	public ParserRule getMinimumRule() {
		return getMinimumAccess().getRule();
	}
	
	//Maximum: {Maximum} "Maximum";
	public MaximumElements getMaximumAccess() {
		return pMaximum;
	}
	
	public ParserRule getMaximumRule() {
		return getMaximumAccess().getRule();
	}
	
	//Average: {Average} "Average";
	public AverageElements getAverageAccess() {
		return pAverage;
	}
	
	public ParserRule getAverageRule() {
		return getAverageAccess().getRule();
	}
	
	//Median: {Median} "Median";
	public MedianElements getMedianAccess() {
		return pMedian;
	}
	
	public ParserRule getMedianRule() {
		return getMedianAccess().getRule();
	}
	
	//StandardDeviation: {StandardDeviation} "Standard" "deviation";
	public StandardDeviationElements getStandardDeviationAccess() {
		return pStandardDeviation;
	}
	
	public ParserRule getStandardDeviationRule() {
		return getStandardDeviationAccess().getRule();
	}
	
	//enum WindowUnit:
	//    SEC="seconds" |
	//    MIN="minutes" |
	//    HOUR="hours" |
	//    DAY="days" |
	//    MEASUREMENT="measurements"
	//;
	public WindowUnitElements getWindowUnitAccess() {
		return eWindowUnit;
	}
	
	public EnumRule getWindowUnitRule() {
		return getWindowUnitAccess().getRule();
	}
	
	//enum ValueUnit:
	//    MILLI="milliseconds" |
	//    SEC="seconds" |
	//    MIN="minutes" |
	//    HOUR="hours" |
	//    LITERS="liters" |
	//    M3="cubic meter" |
	//    Wh="Wh" |
	//    kWh="kWh" |
	//    gCO2eq="gCO2eq" |
	//    kgCO2eq="kgCO2eq"
	//;
	public ValueUnitElements getValueUnitAccess() {
		return eValueUnit;
	}
	
	public EnumRule getValueUnitRule() {
		return getValueUnitAccess().getRule();
	}
	
	//Condition returns ConditionalOp:
	//    "{"
	//        (conditions+=Expression "->" results+=Expression  ";")+
	//        => "otherwise" "->" results+=Expression
	//    "}"
	//;
	public ConditionElements getConditionAccess() {
		return pCondition;
	}
	
	public ParserRule getConditionRule() {
		return getConditionAccess().getRule();
	}
	
	//Expression returns Expression: Or;
	public ExpressionElements getExpressionAccess() {
		return pExpression;
	}
	
	public ParserRule getExpressionRule() {
		return getExpressionAccess().getRule();
	}
	
	//Or returns Expression:
	//    And (
	//        {Or.left=current} "or" right=And
	//    )*;
	public OrElements getOrAccess() {
		return pOr;
	}
	
	public ParserRule getOrRule() {
		return getOrAccess().getRule();
	}
	
	//And returns Expression:
	//    Equality (
	//        {And.left=current} "and" right=Equality
	//    )*;
	public AndElements getAndAccess() {
		return pAnd;
	}
	
	public ParserRule getAndRule() {
		return getAndAccess().getRule();
	}
	
	//Equality returns Expression:
	//    Comparison (
	//        ({Equality.left=current} '==' | {Inequality.left=current} '!=')
	//        right=Comparison
	//    )*;
	public EqualityElements getEqualityAccess() {
		return pEquality;
	}
	
	public ParserRule getEqualityRule() {
		return getEqualityAccess().getRule();
	}
	
	//Comparison returns Expression:
	//    PlusOrMinus (
	//        (
	//            {GreaterEq.left=current} ">=" |
	//            {LessEq.left=current} "<=" |
	//            {Greater.left=current} '>' |
	//            {Less.left=current} "<"
	//        )
	//        right=PlusOrMinus
	//    )*;
	public ComparisonElements getComparisonAccess() {
		return pComparison;
	}
	
	public ParserRule getComparisonRule() {
		return getComparisonAccess().getRule();
	}
	
	//PlusOrMinus returns Expression:
	//    MulOrDiv (
	//        ({Plus.left=current} '+' | {Minus.left=current} '-')
	//        right=MulOrDiv
	//    )*;
	public PlusOrMinusElements getPlusOrMinusAccess() {
		return pPlusOrMinus;
	}
	
	public ParserRule getPlusOrMinusRule() {
		return getPlusOrMinusAccess().getRule();
	}
	
	//MulOrDiv returns Expression:
	//    Primary (
	//        ({Multiply.left=current} '*' | {Divide.left=current} '/')
	//        right=Primary
	//    )*;
	public MulOrDivElements getMulOrDivAccess() {
		return pMulOrDiv;
	}
	
	public ParserRule getMulOrDivRule() {
		return getMulOrDivAccess().getRule();
	}
	
	//Primary returns Expression:
	//    '(' Expression ')' |
	//    {Not} "!" expression=Primary |
	//    {UnaryMinus} "-" expression=Primary |
	//    {AvgOp} "AVERAGE" "(" expressions+=Expression ("," expressions+=Expression)* ")" |
	//    {WeightedSumOp} "WEIGHTED_SUM" "(" expressions+=Expression ":" weights+=Expression ("," expressions+=Expression ":" weights+=Expression)* ")" |
	//    {MinOp} "MIN" "(" expressions+=Expression ("," expressions+=Expression)* ")" |
	//    {MaxOp} "MAX" "(" expressions+=Expression ("," expressions+=Expression)* ")" |
	//    {ThresholdOp} "THRESHOLD" "(" expression=Expression "," threshold=Expression ")" |
	//    Atomic;
	public PrimaryElements getPrimaryAccess() {
		return pPrimary;
	}
	
	public ParserRule getPrimaryRule() {
		return getPrimaryAccess().getRule();
	}
	
	//Atomic returns Expression:
	//    {IntConstant} value=INT |
	//    {RealConstant} value=DOUBLE |
	//    {TextConstant} value=STRING |
	//    {BoolConstant} value=('true' | 'false') |
	//    {UnitConstant} value=DOUBLE unit=ValueUnit |
	//    {EnumLiteralRef} literal=[EnumerationLiteral|FQN] |
	//    {ComputableRef} computable=[Computable]
	//;
	public AtomicElements getAtomicAccess() {
		return pAtomic;
	}
	
	public ParserRule getAtomicRule() {
		return getAtomicAccess().getRule();
	}
	
	//terminal DOUBLE returns ecore::EDouble: INT "." INT;
	public TerminalRule getDOUBLERule() {
		return tDOUBLE;
	}
	
	//terminal FQN returns ecore::EString: ID ("." ID)+;
	public TerminalRule getFQNRule() {
		return tFQN;
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
