/*
 * generated by Xtext 2.41.0
 */
package lu.list.swrdi.formulaKPI.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class KPIFormulaDSLProposalProvider extends AbstractKPIFormulaDSLProposalProvider {
}
