/*
 * generated by Xtext 2.41.0
 */
package lu.list.swrdi.formulaKPI.scoping;

import java.util.List;
import java.util.stream.Collectors;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.EcoreUtil2;
import org.eclipse.xtext.scoping.IScope;
import org.eclipse.xtext.scoping.Scopes;

import lu.list.swrdi.formulaKPI.QualityModelUtils;
import lu.list.swrdi.formulaKPI.model.formulaKPI.Computable;
import lu.list.swrdi.formulaKPI.model.formulaKPI.Metric;
import lu.list.swrdi.formulaKPI.model.formulaKPI.formulaKPIPackage;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class KPIFormulaDSLScopeProvider extends AbstractKPIFormulaDSLScopeProvider {
	
    @Override
    public IScope getScope(EObject context, EReference reference) {
    	QualityModelUtils.updateQualityModelResource();
        if (reference == formulaKPIPackage.Literals.COMPUTABLE_REF__COMPUTABLE) {
            EObject rootElement = EcoreUtil2.getRootContainer(context);
            List<Computable> candidates = EcoreUtil2.getAllContentsOfType(rootElement, Computable.class);
            candidates.addAll(QualityModelUtils.getQualityModelElements());
            return Scopes.scopeFor(candidates, super.getScope(context, reference));
        }
        if (reference == formulaKPIPackage.Literals.COMPUTATION__COMPUTED) {
            EObject rootElement = EcoreUtil2.getRootContainer(context);
            List<Computable> candidates = EcoreUtil2.getAllContentsOfType(rootElement, Computable.class);
            List<Computable> QMCharacNAttr = QualityModelUtils.getQualityModelElements().stream().filter(e -> ! (e instanceof Metric)).collect(Collectors.toList());
            candidates.addAll(QMCharacNAttr);
            return Scopes.scopeFor(candidates, super.getScope(context, reference));
        }
        return super.getScope(context, reference);
    }
}
