/*
 * generated by Xtext 2.41.0
 */
package lu.list.swrdi.formulaKPI.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import lu.list.swrdi.formulaKPI.ide.contentassist.antlr.internal.InternalKPIFormulaDSLParser;
import lu.list.swrdi.formulaKPI.services.KPIFormulaDSLGrammarAccess;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class KPIFormulaDSLParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(KPIFormulaDSLGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, KPIFormulaDSLGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getKPIFormulaDSLAccess().getAlternatives(), "rule__KPIFormulaDSL__Alternatives");
			builder.put(grammarAccess.getDeclarableAccess().getAlternatives(), "rule__Declarable__Alternatives");
			builder.put(grammarAccess.getValueTypeAccess().getAlternatives(), "rule__ValueType__Alternatives");
			builder.put(grammarAccess.getOperationAccess().getAlternatives(), "rule__Operation__Alternatives");
			builder.put(grammarAccess.getTopLevelExpressionAccess().getAlternatives(), "rule__TopLevelExpression__Alternatives");
			builder.put(grammarAccess.getEqualityAccess().getAlternatives_1_0(), "rule__Equality__Alternatives_1_0");
			builder.put(grammarAccess.getComparisonAccess().getAlternatives_1_0(), "rule__Comparison__Alternatives_1_0");
			builder.put(grammarAccess.getPlusOrMinusAccess().getAlternatives_1_0(), "rule__PlusOrMinus__Alternatives_1_0");
			builder.put(grammarAccess.getMulOrDivAccess().getAlternatives_1_0(), "rule__MulOrDiv__Alternatives_1_0");
			builder.put(grammarAccess.getOperatorAccess().getAlternatives(), "rule__Operator__Alternatives");
			builder.put(grammarAccess.getPrimaryAccess().getAlternatives(), "rule__Primary__Alternatives");
			builder.put(grammarAccess.getAtomicAccess().getAlternatives(), "rule__Atomic__Alternatives");
			builder.put(grammarAccess.getAtomicAccess().getValueAlternatives_4_1_0(), "rule__Atomic__ValueAlternatives_4_1_0");
			builder.put(grammarAccess.getWindowUnitAccess().getAlternatives(), "rule__WindowUnit__Alternatives");
			builder.put(grammarAccess.getValueUnitAccess().getAlternatives(), "rule__ValueUnit__Alternatives");
			builder.put(grammarAccess.getComputationAccess().getGroup(), "rule__Computation__Group__0");
			builder.put(grammarAccess.getMetricAccess().getGroup(), "rule__Metric__Group__0");
			builder.put(grammarAccess.getKPIAccess().getGroup(), "rule__KPI__Group__0");
			builder.put(grammarAccess.getIntegerValueAccess().getGroup(), "rule__IntegerValue__Group__0");
			builder.put(grammarAccess.getRealValueAccess().getGroup(), "rule__RealValue__Group__0");
			builder.put(grammarAccess.getTextualValueAccess().getGroup(), "rule__TextualValue__Group__0");
			builder.put(grammarAccess.getBooleanValueAccess().getGroup(), "rule__BooleanValue__Group__0");
			builder.put(grammarAccess.getEnumerationValueAccess().getGroup(), "rule__EnumerationValue__Group__0");
			builder.put(grammarAccess.getAggregationValueAccess().getGroup(), "rule__AggregationValue__Group__0");
			builder.put(grammarAccess.getDriftValueAccess().getGroup(), "rule__DriftValue__Group__0");
			builder.put(grammarAccess.getMinimumAccess().getGroup(), "rule__Minimum__Group__0");
			builder.put(grammarAccess.getMaximumAccess().getGroup(), "rule__Maximum__Group__0");
			builder.put(grammarAccess.getAverageAccess().getGroup(), "rule__Average__Group__0");
			builder.put(grammarAccess.getMedianAccess().getGroup(), "rule__Median__Group__0");
			builder.put(grammarAccess.getStandardDeviationAccess().getGroup(), "rule__StandardDeviation__Group__0");
			builder.put(grammarAccess.getConditionAccess().getGroup(), "rule__Condition__Group__0");
			builder.put(grammarAccess.getConditionAccess().getGroup_2(), "rule__Condition__Group_2__0");
			builder.put(grammarAccess.getOrAccess().getGroup(), "rule__Or__Group__0");
			builder.put(grammarAccess.getOrAccess().getGroup_1(), "rule__Or__Group_1__0");
			builder.put(grammarAccess.getAndAccess().getGroup(), "rule__And__Group__0");
			builder.put(grammarAccess.getAndAccess().getGroup_1(), "rule__And__Group_1__0");
			builder.put(grammarAccess.getEqualityAccess().getGroup(), "rule__Equality__Group__0");
			builder.put(grammarAccess.getEqualityAccess().getGroup_1(), "rule__Equality__Group_1__0");
			builder.put(grammarAccess.getEqualityAccess().getGroup_1_0_0(), "rule__Equality__Group_1_0_0__0");
			builder.put(grammarAccess.getEqualityAccess().getGroup_1_0_1(), "rule__Equality__Group_1_0_1__0");
			builder.put(grammarAccess.getComparisonAccess().getGroup(), "rule__Comparison__Group__0");
			builder.put(grammarAccess.getComparisonAccess().getGroup_1(), "rule__Comparison__Group_1__0");
			builder.put(grammarAccess.getComparisonAccess().getGroup_1_0_0(), "rule__Comparison__Group_1_0_0__0");
			builder.put(grammarAccess.getComparisonAccess().getGroup_1_0_1(), "rule__Comparison__Group_1_0_1__0");
			builder.put(grammarAccess.getComparisonAccess().getGroup_1_0_2(), "rule__Comparison__Group_1_0_2__0");
			builder.put(grammarAccess.getComparisonAccess().getGroup_1_0_3(), "rule__Comparison__Group_1_0_3__0");
			builder.put(grammarAccess.getPlusOrMinusAccess().getGroup(), "rule__PlusOrMinus__Group__0");
			builder.put(grammarAccess.getPlusOrMinusAccess().getGroup_1(), "rule__PlusOrMinus__Group_1__0");
			builder.put(grammarAccess.getPlusOrMinusAccess().getGroup_1_0_0(), "rule__PlusOrMinus__Group_1_0_0__0");
			builder.put(grammarAccess.getPlusOrMinusAccess().getGroup_1_0_1(), "rule__PlusOrMinus__Group_1_0_1__0");
			builder.put(grammarAccess.getMulOrDivAccess().getGroup(), "rule__MulOrDiv__Group__0");
			builder.put(grammarAccess.getMulOrDivAccess().getGroup_1(), "rule__MulOrDiv__Group_1__0");
			builder.put(grammarAccess.getMulOrDivAccess().getGroup_1_0_0(), "rule__MulOrDiv__Group_1_0_0__0");
			builder.put(grammarAccess.getMulOrDivAccess().getGroup_1_0_1(), "rule__MulOrDiv__Group_1_0_1__0");
			builder.put(grammarAccess.getOperatorAccess().getGroup_0(), "rule__Operator__Group_0__0");
			builder.put(grammarAccess.getOperatorAccess().getGroup_1(), "rule__Operator__Group_1__0");
			builder.put(grammarAccess.getOperatorAccess().getGroup_1_3(), "rule__Operator__Group_1_3__0");
			builder.put(grammarAccess.getOperatorAccess().getGroup_2(), "rule__Operator__Group_2__0");
			builder.put(grammarAccess.getOperatorAccess().getGroup_3(), "rule__Operator__Group_3__0");
			builder.put(grammarAccess.getOperatorAccess().getGroup_4(), "rule__Operator__Group_4__0");
			builder.put(grammarAccess.getOperatorAccess().getGroup_5(), "rule__Operator__Group_5__0");
			builder.put(grammarAccess.getOperatorAccess().getGroup_6(), "rule__Operator__Group_6__0");
			builder.put(grammarAccess.getOperatorAccess().getGroup_7(), "rule__Operator__Group_7__0");
			builder.put(grammarAccess.getOperatorAccess().getGroup_7_7(), "rule__Operator__Group_7_7__0");
			builder.put(grammarAccess.getOperatorAccess().getGroup_8(), "rule__Operator__Group_8__0");
			builder.put(grammarAccess.getOperatorAccess().getGroup_8_9(), "rule__Operator__Group_8_9__0");
			builder.put(grammarAccess.getOperatorAccess().getGroup_9(), "rule__Operator__Group_9__0");
			builder.put(grammarAccess.getOperatorAccess().getGroup_9_7(), "rule__Operator__Group_9_7__0");
			builder.put(grammarAccess.getPrimaryAccess().getGroup_0(), "rule__Primary__Group_0__0");
			builder.put(grammarAccess.getPrimaryAccess().getGroup_1(), "rule__Primary__Group_1__0");
			builder.put(grammarAccess.getPrimaryAccess().getGroup_2(), "rule__Primary__Group_2__0");
			builder.put(grammarAccess.getAtomicAccess().getGroup_0(), "rule__Atomic__Group_0__0");
			builder.put(grammarAccess.getAtomicAccess().getGroup_1(), "rule__Atomic__Group_1__0");
			builder.put(grammarAccess.getAtomicAccess().getGroup_2(), "rule__Atomic__Group_2__0");
			builder.put(grammarAccess.getAtomicAccess().getGroup_3(), "rule__Atomic__Group_3__0");
			builder.put(grammarAccess.getAtomicAccess().getGroup_4(), "rule__Atomic__Group_4__0");
			builder.put(grammarAccess.getAtomicAccess().getGroup_5(), "rule__Atomic__Group_5__0");
			builder.put(grammarAccess.getAtomicAccess().getGroup_6(), "rule__Atomic__Group_6__0");
			builder.put(grammarAccess.getAtomicAccess().getGroup_7(), "rule__Atomic__Group_7__0");
			builder.put(grammarAccess.getKPIFormulaDSLAccess().getDeclarationsAssignment_0(), "rule__KPIFormulaDSL__DeclarationsAssignment_0");
			builder.put(grammarAccess.getKPIFormulaDSLAccess().getComputationsAssignment_1(), "rule__KPIFormulaDSL__ComputationsAssignment_1");
			builder.put(grammarAccess.getDeclarationAccess().getDeclaredAssignment(), "rule__Declaration__DeclaredAssignment");
			builder.put(grammarAccess.getComputationAccess().getComputedAssignment_0(), "rule__Computation__ComputedAssignment_0");
			builder.put(grammarAccess.getComputationAccess().getFormulaAssignment_2(), "rule__Computation__FormulaAssignment_2");
			builder.put(grammarAccess.getMetricAccess().getNameAssignment_0(), "rule__Metric__NameAssignment_0");
			builder.put(grammarAccess.getMetricAccess().getTypeAssignment_3(), "rule__Metric__TypeAssignment_3");
			builder.put(grammarAccess.getKPIAccess().getNameAssignment_1(), "rule__KPI__NameAssignment_1");
			builder.put(grammarAccess.getKPIAccess().getTypeAssignment_4(), "rule__KPI__TypeAssignment_4");
			builder.put(grammarAccess.getEnumerationValueAccess().getLiteralsAssignment_1(), "rule__EnumerationValue__LiteralsAssignment_1");
			builder.put(grammarAccess.getEnumerationLiteralAccess().getNameAssignment(), "rule__EnumerationLiteral__NameAssignment");
			builder.put(grammarAccess.getUnitValueAccess().getUnitAssignment(), "rule__UnitValue__UnitAssignment");
			builder.put(grammarAccess.getAggregationValueAccess().getOperationAssignment_1(), "rule__AggregationValue__OperationAssignment_1");
			builder.put(grammarAccess.getAggregationValueAccess().getWindowAssignment_3(), "rule__AggregationValue__WindowAssignment_3");
			builder.put(grammarAccess.getAggregationValueAccess().getWindowUnitAssignment_4(), "rule__AggregationValue__WindowUnitAssignment_4");
			builder.put(grammarAccess.getDriftValueAccess().getOperationAssignment_2(), "rule__DriftValue__OperationAssignment_2");
			builder.put(grammarAccess.getDriftValueAccess().getWindowAssignment_4(), "rule__DriftValue__WindowAssignment_4");
			builder.put(grammarAccess.getDriftValueAccess().getWindowUnitAssignment_5(), "rule__DriftValue__WindowUnitAssignment_5");
			builder.put(grammarAccess.getConditionAccess().getConditionsAssignment_2_0(), "rule__Condition__ConditionsAssignment_2_0");
			builder.put(grammarAccess.getConditionAccess().getResultsAssignment_2_2(), "rule__Condition__ResultsAssignment_2_2");
			builder.put(grammarAccess.getConditionAccess().getResultsAssignment_5(), "rule__Condition__ResultsAssignment_5");
			builder.put(grammarAccess.getOrAccess().getRightAssignment_1_2(), "rule__Or__RightAssignment_1_2");
			builder.put(grammarAccess.getAndAccess().getRightAssignment_1_2(), "rule__And__RightAssignment_1_2");
			builder.put(grammarAccess.getEqualityAccess().getRightAssignment_1_1(), "rule__Equality__RightAssignment_1_1");
			builder.put(grammarAccess.getComparisonAccess().getRightAssignment_1_1(), "rule__Comparison__RightAssignment_1_1");
			builder.put(grammarAccess.getPlusOrMinusAccess().getRightAssignment_1_1(), "rule__PlusOrMinus__RightAssignment_1_1");
			builder.put(grammarAccess.getMulOrDivAccess().getRightAssignment_1_1(), "rule__MulOrDiv__RightAssignment_1_1");
			builder.put(grammarAccess.getOperatorAccess().getExpressionAssignment_0_2(), "rule__Operator__ExpressionAssignment_0_2");
			builder.put(grammarAccess.getOperatorAccess().getElementsAssignment_1_2(), "rule__Operator__ElementsAssignment_1_2");
			builder.put(grammarAccess.getOperatorAccess().getElementsAssignment_1_3_1(), "rule__Operator__ElementsAssignment_1_3_1");
			builder.put(grammarAccess.getOperatorAccess().getListAssignment_2_3(), "rule__Operator__ListAssignment_2_3");
			builder.put(grammarAccess.getOperatorAccess().getListAssignment_3_3(), "rule__Operator__ListAssignment_3_3");
			builder.put(grammarAccess.getOperatorAccess().getWeightsAssignment_3_5(), "rule__Operator__WeightsAssignment_3_5");
			builder.put(grammarAccess.getOperatorAccess().getListAssignment_4_3(), "rule__Operator__ListAssignment_4_3");
			builder.put(grammarAccess.getOperatorAccess().getListAssignment_5_3(), "rule__Operator__ListAssignment_5_3");
			builder.put(grammarAccess.getOperatorAccess().getExpressionAssignment_6_3(), "rule__Operator__ExpressionAssignment_6_3");
			builder.put(grammarAccess.getOperatorAccess().getThresholdAssignment_6_5(), "rule__Operator__ThresholdAssignment_6_5");
			builder.put(grammarAccess.getOperatorAccess().getExpressionAssignment_7_2(), "rule__Operator__ExpressionAssignment_7_2");
			builder.put(grammarAccess.getOperatorAccess().getIteratorsAssignment_7_4(), "rule__Operator__IteratorsAssignment_7_4");
			builder.put(grammarAccess.getOperatorAccess().getListsAssignment_7_6(), "rule__Operator__ListsAssignment_7_6");
			builder.put(grammarAccess.getOperatorAccess().getIteratorsAssignment_7_7_1(), "rule__Operator__IteratorsAssignment_7_7_1");
			builder.put(grammarAccess.getOperatorAccess().getListsAssignment_7_7_3(), "rule__Operator__ListsAssignment_7_7_3");
			builder.put(grammarAccess.getOperatorAccess().getExpressionAssignment_8_2(), "rule__Operator__ExpressionAssignment_8_2");
			builder.put(grammarAccess.getOperatorAccess().getAccumulatorAssignment_8_4(), "rule__Operator__AccumulatorAssignment_8_4");
			builder.put(grammarAccess.getOperatorAccess().getIteratorsAssignment_8_6(), "rule__Operator__IteratorsAssignment_8_6");
			builder.put(grammarAccess.getOperatorAccess().getListsAssignment_8_8(), "rule__Operator__ListsAssignment_8_8");
			builder.put(grammarAccess.getOperatorAccess().getIteratorsAssignment_8_9_1(), "rule__Operator__IteratorsAssignment_8_9_1");
			builder.put(grammarAccess.getOperatorAccess().getListsAssignment_8_9_3(), "rule__Operator__ListsAssignment_8_9_3");
			builder.put(grammarAccess.getOperatorAccess().getExpressionAssignment_9_2(), "rule__Operator__ExpressionAssignment_9_2");
			builder.put(grammarAccess.getOperatorAccess().getIteratorsAssignment_9_4(), "rule__Operator__IteratorsAssignment_9_4");
			builder.put(grammarAccess.getOperatorAccess().getListsAssignment_9_6(), "rule__Operator__ListsAssignment_9_6");
			builder.put(grammarAccess.getOperatorAccess().getIteratorsAssignment_9_7_1(), "rule__Operator__IteratorsAssignment_9_7_1");
			builder.put(grammarAccess.getOperatorAccess().getListsAssignment_9_7_3(), "rule__Operator__ListsAssignment_9_7_3");
			builder.put(grammarAccess.getPrimaryAccess().getExpressionAssignment_1_2(), "rule__Primary__ExpressionAssignment_1_2");
			builder.put(grammarAccess.getPrimaryAccess().getExpressionAssignment_2_2(), "rule__Primary__ExpressionAssignment_2_2");
			builder.put(grammarAccess.getListIteratorAccess().getNameAssignment(), "rule__ListIterator__NameAssignment");
			builder.put(grammarAccess.getAtomicAccess().getValueAssignment_1_1(), "rule__Atomic__ValueAssignment_1_1");
			builder.put(grammarAccess.getAtomicAccess().getValueAssignment_2_1(), "rule__Atomic__ValueAssignment_2_1");
			builder.put(grammarAccess.getAtomicAccess().getValueAssignment_3_1(), "rule__Atomic__ValueAssignment_3_1");
			builder.put(grammarAccess.getAtomicAccess().getValueAssignment_4_1(), "rule__Atomic__ValueAssignment_4_1");
			builder.put(grammarAccess.getAtomicAccess().getValueAssignment_5_1(), "rule__Atomic__ValueAssignment_5_1");
			builder.put(grammarAccess.getAtomicAccess().getUnitAssignment_5_2(), "rule__Atomic__UnitAssignment_5_2");
			builder.put(grammarAccess.getAtomicAccess().getLiteralAssignment_6_1(), "rule__Atomic__LiteralAssignment_6_1");
			builder.put(grammarAccess.getAtomicAccess().getComputableAssignment_7_1(), "rule__Atomic__ComputableAssignment_7_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private KPIFormulaDSLGrammarAccess grammarAccess;

	@Override
	protected InternalKPIFormulaDSLParser createParser() {
		InternalKPIFormulaDSLParser result = new InternalKPIFormulaDSLParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public KPIFormulaDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(KPIFormulaDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
