/**
 * generated by Xtext 2.41.0
 */
package lu.list.swrdi.formulaKPI.formatting2;

import com.google.inject.Inject;
import java.util.Arrays;
import lu.list.swrdi.formulaKPI.model.formulaKPI.Computation;
import lu.list.swrdi.formulaKPI.model.formulaKPI.Declarable;
import lu.list.swrdi.formulaKPI.model.formulaKPI.Declaration;
import lu.list.swrdi.formulaKPI.model.formulaKPI.KPIFormula;
import lu.list.swrdi.formulaKPI.services.KPIFormulaDSLGrammarAccess;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;
import org.eclipse.xtext.xbase.lib.XbaseGenerated;

@SuppressWarnings("all")
public class KPIFormulaDSLFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private KPIFormulaDSLGrammarAccess _kPIFormulaDSLGrammarAccess;

  protected void _format(final KPIFormula kPIFormula, @Extension final IFormattableDocument document) {
    EList<Declaration> _declarations = kPIFormula.getDeclarations();
    for (final Declaration declaration : _declarations) {
      document.<Declaration>format(declaration);
    }
    EList<Computation> _computations = kPIFormula.getComputations();
    for (final Computation computation : _computations) {
      document.<Computation>format(computation);
    }
  }

  protected void _format(final Declaration declaration, @Extension final IFormattableDocument document) {
    document.<Declarable>format(declaration.getDeclared());
  }

  @XbaseGenerated
  public void format(final Object declaration, final IFormattableDocument document) {
    if (declaration instanceof XtextResource) {
      _format((XtextResource)declaration, document);
      return;
    } else if (declaration instanceof Declaration) {
      _format((Declaration)declaration, document);
      return;
    } else if (declaration instanceof KPIFormula) {
      _format((KPIFormula)declaration, document);
      return;
    } else if (declaration instanceof EObject) {
      _format((EObject)declaration, document);
      return;
    } else if (declaration == null) {
      _format((Void)null, document);
      return;
    } else if (declaration != null) {
      _format(declaration, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(declaration, document).toString());
    }
  }
}
