/*
 * generated by Xtext 2.41.0
 */
package lu.list.swrdi.formulaKPI.ui;

import com.google.inject.Injector;
import lu.list.swrdi.formulaKPI.ui.internal.FormulaKPIActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class KPIFormulaDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(FormulaKPIActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		FormulaKPIActivator activator = FormulaKPIActivator.getInstance();
		return activator != null ? activator.getInjector(FormulaKPIActivator.LU_LIST_SWRDI_FORMULAKPI_KPIFORMULADSL) : null;
	}

}
