/*
 * generated by Xtext 2.41.0
 */
package lu.list.swrdi.formulaKPI.ui.tests;

import com.google.inject.Injector;
import lu.list.swrdi.formulaKPI.ui.internal.FormulaKPIActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class KPIFormulaDSLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return FormulaKPIActivator.getInstance().getInjector("lu.list.swrdi.formulaKPI.KPIFormulaDSL");
	}

}
