/*
 * generated by Xtext 2.41.0
 */
package lu.list.swrdi.formulaKPI.tests

import com.google.inject.Inject
import lu.list.swrdi.formulaKPI.model.formulaKPI.KPIFormula
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith

@ExtendWith(InjectionExtension)
@InjectWith(KPIFormulaDSLInjectorProvider)
class KPIFormulaDSLParsingTest {
	@Inject
	ParseHelper<KPIFormula> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			KPI thekpi of type real
			thekpi = 0.5
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
}
