/*
 * generated by Xtext 2.41.0
 */
package lu.list.swrdi.formulaKPI.serializer;

import com.google.inject.Inject;
import java.util.Set;
import lu.list.swrdi.formulaKPI.model.formulaKPI.Accumulator;
import lu.list.swrdi.formulaKPI.model.formulaKPI.AggregationValue;
import lu.list.swrdi.formulaKPI.model.formulaKPI.And;
import lu.list.swrdi.formulaKPI.model.formulaKPI.Average;
import lu.list.swrdi.formulaKPI.model.formulaKPI.AvgOp;
import lu.list.swrdi.formulaKPI.model.formulaKPI.BoolConstant;
import lu.list.swrdi.formulaKPI.model.formulaKPI.BooleanValue;
import lu.list.swrdi.formulaKPI.model.formulaKPI.ComputableRef;
import lu.list.swrdi.formulaKPI.model.formulaKPI.Computation;
import lu.list.swrdi.formulaKPI.model.formulaKPI.ConditionalOp;
import lu.list.swrdi.formulaKPI.model.formulaKPI.Declaration;
import lu.list.swrdi.formulaKPI.model.formulaKPI.Divide;
import lu.list.swrdi.formulaKPI.model.formulaKPI.DriftValue;
import lu.list.swrdi.formulaKPI.model.formulaKPI.EnumLiteralRef;
import lu.list.swrdi.formulaKPI.model.formulaKPI.EnumerationLiteral;
import lu.list.swrdi.formulaKPI.model.formulaKPI.EnumerationValue;
import lu.list.swrdi.formulaKPI.model.formulaKPI.Equality;
import lu.list.swrdi.formulaKPI.model.formulaKPI.Greater;
import lu.list.swrdi.formulaKPI.model.formulaKPI.GreaterEq;
import lu.list.swrdi.formulaKPI.model.formulaKPI.Inequality;
import lu.list.swrdi.formulaKPI.model.formulaKPI.IntConstant;
import lu.list.swrdi.formulaKPI.model.formulaKPI.IntegerValue;
import lu.list.swrdi.formulaKPI.model.formulaKPI.KPI;
import lu.list.swrdi.formulaKPI.model.formulaKPI.KPIFormula;
import lu.list.swrdi.formulaKPI.model.formulaKPI.Less;
import lu.list.swrdi.formulaKPI.model.formulaKPI.LessEq;
import lu.list.swrdi.formulaKPI.model.formulaKPI.ListFilter;
import lu.list.swrdi.formulaKPI.model.formulaKPI.ListIteration;
import lu.list.swrdi.formulaKPI.model.formulaKPI.ListIterator;
import lu.list.swrdi.formulaKPI.model.formulaKPI.ListLiteral;
import lu.list.swrdi.formulaKPI.model.formulaKPI.ListReduce;
import lu.list.swrdi.formulaKPI.model.formulaKPI.ListSize;
import lu.list.swrdi.formulaKPI.model.formulaKPI.MaxOp;
import lu.list.swrdi.formulaKPI.model.formulaKPI.Maximum;
import lu.list.swrdi.formulaKPI.model.formulaKPI.Median;
import lu.list.swrdi.formulaKPI.model.formulaKPI.Metric;
import lu.list.swrdi.formulaKPI.model.formulaKPI.MinOp;
import lu.list.swrdi.formulaKPI.model.formulaKPI.Minimum;
import lu.list.swrdi.formulaKPI.model.formulaKPI.Minus;
import lu.list.swrdi.formulaKPI.model.formulaKPI.Multiply;
import lu.list.swrdi.formulaKPI.model.formulaKPI.Not;
import lu.list.swrdi.formulaKPI.model.formulaKPI.Or;
import lu.list.swrdi.formulaKPI.model.formulaKPI.Plus;
import lu.list.swrdi.formulaKPI.model.formulaKPI.RealConstant;
import lu.list.swrdi.formulaKPI.model.formulaKPI.RealValue;
import lu.list.swrdi.formulaKPI.model.formulaKPI.StandardDeviation;
import lu.list.swrdi.formulaKPI.model.formulaKPI.SumOp;
import lu.list.swrdi.formulaKPI.model.formulaKPI.TextConstant;
import lu.list.swrdi.formulaKPI.model.formulaKPI.TextualValue;
import lu.list.swrdi.formulaKPI.model.formulaKPI.ThresholdOp;
import lu.list.swrdi.formulaKPI.model.formulaKPI.UnaryMinus;
import lu.list.swrdi.formulaKPI.model.formulaKPI.UnitConstant;
import lu.list.swrdi.formulaKPI.model.formulaKPI.UnitValue;
import lu.list.swrdi.formulaKPI.model.formulaKPI.WeightedSumOp;
import lu.list.swrdi.formulaKPI.model.formulaKPI.formulaKPIPackage;
import lu.list.swrdi.formulaKPI.services.KPIFormulaDSLGrammarAccess;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;

@SuppressWarnings("all")
public class KPIFormulaDSLSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private KPIFormulaDSLGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == formulaKPIPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case formulaKPIPackage.ACCUMULATOR:
				sequence_Atomic(context, (Accumulator) semanticObject); 
				return; 
			case formulaKPIPackage.AGGREGATION_VALUE:
				sequence_AggregationValue(context, (AggregationValue) semanticObject); 
				return; 
			case formulaKPIPackage.AND:
				sequence_And(context, (And) semanticObject); 
				return; 
			case formulaKPIPackage.AVERAGE:
				sequence_Average(context, (Average) semanticObject); 
				return; 
			case formulaKPIPackage.AVG_OP:
				sequence_Operator(context, (AvgOp) semanticObject); 
				return; 
			case formulaKPIPackage.BOOL_CONSTANT:
				sequence_Atomic(context, (BoolConstant) semanticObject); 
				return; 
			case formulaKPIPackage.BOOLEAN_VALUE:
				sequence_BooleanValue(context, (BooleanValue) semanticObject); 
				return; 
			case formulaKPIPackage.COMPUTABLE_REF:
				sequence_Atomic(context, (ComputableRef) semanticObject); 
				return; 
			case formulaKPIPackage.COMPUTATION:
				sequence_Computation(context, (Computation) semanticObject); 
				return; 
			case formulaKPIPackage.CONDITIONAL_OP:
				sequence_Condition(context, (ConditionalOp) semanticObject); 
				return; 
			case formulaKPIPackage.DECLARATION:
				sequence_Declaration(context, (Declaration) semanticObject); 
				return; 
			case formulaKPIPackage.DIVIDE:
				sequence_MulOrDiv(context, (Divide) semanticObject); 
				return; 
			case formulaKPIPackage.DRIFT_VALUE:
				sequence_DriftValue(context, (DriftValue) semanticObject); 
				return; 
			case formulaKPIPackage.ENUM_LITERAL_REF:
				sequence_Atomic(context, (EnumLiteralRef) semanticObject); 
				return; 
			case formulaKPIPackage.ENUMERATION_LITERAL:
				sequence_EnumerationLiteral(context, (EnumerationLiteral) semanticObject); 
				return; 
			case formulaKPIPackage.ENUMERATION_VALUE:
				sequence_EnumerationValue(context, (EnumerationValue) semanticObject); 
				return; 
			case formulaKPIPackage.EQUALITY:
				sequence_Equality(context, (Equality) semanticObject); 
				return; 
			case formulaKPIPackage.GREATER:
				sequence_Comparison(context, (Greater) semanticObject); 
				return; 
			case formulaKPIPackage.GREATER_EQ:
				sequence_Comparison(context, (GreaterEq) semanticObject); 
				return; 
			case formulaKPIPackage.INEQUALITY:
				sequence_Equality(context, (Inequality) semanticObject); 
				return; 
			case formulaKPIPackage.INT_CONSTANT:
				sequence_Atomic(context, (IntConstant) semanticObject); 
				return; 
			case formulaKPIPackage.INTEGER_VALUE:
				sequence_IntegerValue(context, (IntegerValue) semanticObject); 
				return; 
			case formulaKPIPackage.KPI:
				sequence_KPI(context, (KPI) semanticObject); 
				return; 
			case formulaKPIPackage.KPI_FORMULA:
				sequence_KPIFormulaDSL(context, (KPIFormula) semanticObject); 
				return; 
			case formulaKPIPackage.LESS:
				sequence_Comparison(context, (Less) semanticObject); 
				return; 
			case formulaKPIPackage.LESS_EQ:
				sequence_Comparison(context, (LessEq) semanticObject); 
				return; 
			case formulaKPIPackage.LIST_FILTER:
				sequence_Operator(context, (ListFilter) semanticObject); 
				return; 
			case formulaKPIPackage.LIST_ITERATION:
				sequence_Operator(context, (ListIteration) semanticObject); 
				return; 
			case formulaKPIPackage.LIST_ITERATOR:
				sequence_ListIterator(context, (ListIterator) semanticObject); 
				return; 
			case formulaKPIPackage.LIST_LITERAL:
				sequence_Operator(context, (ListLiteral) semanticObject); 
				return; 
			case formulaKPIPackage.LIST_REDUCE:
				sequence_Operator(context, (ListReduce) semanticObject); 
				return; 
			case formulaKPIPackage.LIST_SIZE:
				sequence_Operator(context, (ListSize) semanticObject); 
				return; 
			case formulaKPIPackage.MAX_OP:
				sequence_Operator(context, (MaxOp) semanticObject); 
				return; 
			case formulaKPIPackage.MAXIMUM:
				sequence_Maximum(context, (Maximum) semanticObject); 
				return; 
			case formulaKPIPackage.MEDIAN:
				sequence_Median(context, (Median) semanticObject); 
				return; 
			case formulaKPIPackage.METRIC:
				sequence_Metric(context, (Metric) semanticObject); 
				return; 
			case formulaKPIPackage.MIN_OP:
				sequence_Operator(context, (MinOp) semanticObject); 
				return; 
			case formulaKPIPackage.MINIMUM:
				sequence_Minimum(context, (Minimum) semanticObject); 
				return; 
			case formulaKPIPackage.MINUS:
				sequence_PlusOrMinus(context, (Minus) semanticObject); 
				return; 
			case formulaKPIPackage.MULTIPLY:
				sequence_MulOrDiv(context, (Multiply) semanticObject); 
				return; 
			case formulaKPIPackage.NOT:
				sequence_Primary(context, (Not) semanticObject); 
				return; 
			case formulaKPIPackage.OR:
				sequence_Or(context, (Or) semanticObject); 
				return; 
			case formulaKPIPackage.PLUS:
				sequence_PlusOrMinus(context, (Plus) semanticObject); 
				return; 
			case formulaKPIPackage.REAL_CONSTANT:
				sequence_Atomic(context, (RealConstant) semanticObject); 
				return; 
			case formulaKPIPackage.REAL_VALUE:
				sequence_RealValue(context, (RealValue) semanticObject); 
				return; 
			case formulaKPIPackage.STANDARD_DEVIATION:
				sequence_StandardDeviation(context, (StandardDeviation) semanticObject); 
				return; 
			case formulaKPIPackage.SUM_OP:
				sequence_Operator(context, (SumOp) semanticObject); 
				return; 
			case formulaKPIPackage.TEXT_CONSTANT:
				sequence_Atomic(context, (TextConstant) semanticObject); 
				return; 
			case formulaKPIPackage.TEXTUAL_VALUE:
				sequence_TextualValue(context, (TextualValue) semanticObject); 
				return; 
			case formulaKPIPackage.THRESHOLD_OP:
				sequence_Operator(context, (ThresholdOp) semanticObject); 
				return; 
			case formulaKPIPackage.UNARY_MINUS:
				sequence_Primary(context, (UnaryMinus) semanticObject); 
				return; 
			case formulaKPIPackage.UNIT_CONSTANT:
				sequence_Atomic(context, (UnitConstant) semanticObject); 
				return; 
			case formulaKPIPackage.UNIT_VALUE:
				sequence_UnitValue(context, (UnitValue) semanticObject); 
				return; 
			case formulaKPIPackage.WEIGHTED_SUM_OP:
				sequence_Operator(context, (WeightedSumOp) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     ValueType returns AggregationValue
	 *     AggregationValue returns AggregationValue
	 *
	 * Constraint:
	 *     (operation=Operation window=INT windowUnit=WindowUnit)
	 * </pre>
	 */
	protected void sequence_AggregationValue(ISerializationContext context, AggregationValue semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, formulaKPIPackage.Literals.AGGREGATION_VALUE__OPERATION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, formulaKPIPackage.Literals.AGGREGATION_VALUE__OPERATION));
			if (transientValues.isValueTransient(semanticObject, formulaKPIPackage.Literals.AGGREGATION_VALUE__WINDOW) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, formulaKPIPackage.Literals.AGGREGATION_VALUE__WINDOW));
			if (transientValues.isValueTransient(semanticObject, formulaKPIPackage.Literals.AGGREGATION_VALUE__WINDOW_UNIT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, formulaKPIPackage.Literals.AGGREGATION_VALUE__WINDOW_UNIT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getAggregationValueAccess().getOperationOperationParserRuleCall_1_0(), semanticObject.getOperation());
		feeder.accept(grammarAccess.getAggregationValueAccess().getWindowINTTerminalRuleCall_3_0(), semanticObject.getWindow());
		feeder.accept(grammarAccess.getAggregationValueAccess().getWindowUnitWindowUnitEnumRuleCall_4_0(), semanticObject.getWindowUnit());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     TopLevelExpression returns And
	 *     Expression returns And
	 *     Or returns And
	 *     Or.Or_1_0 returns And
	 *     And returns And
	 *     And.And_1_0 returns And
	 *     Equality returns And
	 *     Equality.Equality_1_0_0_0 returns And
	 *     Equality.Inequality_1_0_1_0 returns And
	 *     Comparison returns And
	 *     Comparison.GreaterEq_1_0_0_0 returns And
	 *     Comparison.LessEq_1_0_1_0 returns And
	 *     Comparison.Greater_1_0_2_0 returns And
	 *     Comparison.Less_1_0_3_0 returns And
	 *     PlusOrMinus returns And
	 *     PlusOrMinus.Plus_1_0_0_0 returns And
	 *     PlusOrMinus.Minus_1_0_1_0 returns And
	 *     MulOrDiv returns And
	 *     MulOrDiv.Multiply_1_0_0_0 returns And
	 *     MulOrDiv.Divide_1_0_1_0 returns And
	 *     Operator returns And
	 *     Primary returns And
	 *
	 * Constraint:
	 *     (left=And_And_1_0 right=Equality)
	 * </pre>
	 */
	protected void sequence_And(ISerializationContext context, And semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, formulaKPIPackage.Literals.BIN_OP__LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, formulaKPIPackage.Literals.BIN_OP__LEFT));
			if (transientValues.isValueTransient(semanticObject, formulaKPIPackage.Literals.BIN_OP__RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, formulaKPIPackage.Literals.BIN_OP__RIGHT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getAndAccess().getAndLeftAction_1_0(), semanticObject.getLeft());
		feeder.accept(grammarAccess.getAndAccess().getRightEqualityParserRuleCall_1_2_0(), semanticObject.getRight());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     TopLevelExpression returns Accumulator
	 *     Expression returns Accumulator
	 *     Or returns Accumulator
	 *     Or.Or_1_0 returns Accumulator
	 *     And returns Accumulator
	 *     And.And_1_0 returns Accumulator
	 *     Equality returns Accumulator
	 *     Equality.Equality_1_0_0_0 returns Accumulator
	 *     Equality.Inequality_1_0_1_0 returns Accumulator
	 *     Comparison returns Accumulator
	 *     Comparison.GreaterEq_1_0_0_0 returns Accumulator
	 *     Comparison.LessEq_1_0_1_0 returns Accumulator
	 *     Comparison.Greater_1_0_2_0 returns Accumulator
	 *     Comparison.Less_1_0_3_0 returns Accumulator
	 *     PlusOrMinus returns Accumulator
	 *     PlusOrMinus.Plus_1_0_0_0 returns Accumulator
	 *     PlusOrMinus.Minus_1_0_1_0 returns Accumulator
	 *     MulOrDiv returns Accumulator
	 *     MulOrDiv.Multiply_1_0_0_0 returns Accumulator
	 *     MulOrDiv.Divide_1_0_1_0 returns Accumulator
	 *     Operator returns Accumulator
	 *     Primary returns Accumulator
	 *     Atomic returns Accumulator
	 *
	 * Constraint:
	 *     {Accumulator}
	 * </pre>
	 */
	protected void sequence_Atomic(ISerializationContext context, Accumulator semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     TopLevelExpression returns BoolConstant
	 *     Expression returns BoolConstant
	 *     Or returns BoolConstant
	 *     Or.Or_1_0 returns BoolConstant
	 *     And returns BoolConstant
	 *     And.And_1_0 returns BoolConstant
	 *     Equality returns BoolConstant
	 *     Equality.Equality_1_0_0_0 returns BoolConstant
	 *     Equality.Inequality_1_0_1_0 returns BoolConstant
	 *     Comparison returns BoolConstant
	 *     Comparison.GreaterEq_1_0_0_0 returns BoolConstant
	 *     Comparison.LessEq_1_0_1_0 returns BoolConstant
	 *     Comparison.Greater_1_0_2_0 returns BoolConstant
	 *     Comparison.Less_1_0_3_0 returns BoolConstant
	 *     PlusOrMinus returns BoolConstant
	 *     PlusOrMinus.Plus_1_0_0_0 returns BoolConstant
	 *     PlusOrMinus.Minus_1_0_1_0 returns BoolConstant
	 *     MulOrDiv returns BoolConstant
	 *     MulOrDiv.Multiply_1_0_0_0 returns BoolConstant
	 *     MulOrDiv.Divide_1_0_1_0 returns BoolConstant
	 *     Operator returns BoolConstant
	 *     Primary returns BoolConstant
	 *     Atomic returns BoolConstant
	 *
	 * Constraint:
	 *     (value='true' | value='false')
	 * </pre>
	 */
	protected void sequence_Atomic(ISerializationContext context, BoolConstant semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     TopLevelExpression returns ComputableRef
	 *     Expression returns ComputableRef
	 *     Or returns ComputableRef
	 *     Or.Or_1_0 returns ComputableRef
	 *     And returns ComputableRef
	 *     And.And_1_0 returns ComputableRef
	 *     Equality returns ComputableRef
	 *     Equality.Equality_1_0_0_0 returns ComputableRef
	 *     Equality.Inequality_1_0_1_0 returns ComputableRef
	 *     Comparison returns ComputableRef
	 *     Comparison.GreaterEq_1_0_0_0 returns ComputableRef
	 *     Comparison.LessEq_1_0_1_0 returns ComputableRef
	 *     Comparison.Greater_1_0_2_0 returns ComputableRef
	 *     Comparison.Less_1_0_3_0 returns ComputableRef
	 *     PlusOrMinus returns ComputableRef
	 *     PlusOrMinus.Plus_1_0_0_0 returns ComputableRef
	 *     PlusOrMinus.Minus_1_0_1_0 returns ComputableRef
	 *     MulOrDiv returns ComputableRef
	 *     MulOrDiv.Multiply_1_0_0_0 returns ComputableRef
	 *     MulOrDiv.Divide_1_0_1_0 returns ComputableRef
	 *     Operator returns ComputableRef
	 *     Primary returns ComputableRef
	 *     Atomic returns ComputableRef
	 *
	 * Constraint:
	 *     computable=[Computable|ID]
	 * </pre>
	 */
	protected void sequence_Atomic(ISerializationContext context, ComputableRef semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, formulaKPIPackage.Literals.COMPUTABLE_REF__COMPUTABLE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, formulaKPIPackage.Literals.COMPUTABLE_REF__COMPUTABLE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getAtomicAccess().getComputableComputableIDTerminalRuleCall_7_1_0_1(), semanticObject.eGet(formulaKPIPackage.Literals.COMPUTABLE_REF__COMPUTABLE, false));
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     TopLevelExpression returns EnumLiteralRef
	 *     Expression returns EnumLiteralRef
	 *     Or returns EnumLiteralRef
	 *     Or.Or_1_0 returns EnumLiteralRef
	 *     And returns EnumLiteralRef
	 *     And.And_1_0 returns EnumLiteralRef
	 *     Equality returns EnumLiteralRef
	 *     Equality.Equality_1_0_0_0 returns EnumLiteralRef
	 *     Equality.Inequality_1_0_1_0 returns EnumLiteralRef
	 *     Comparison returns EnumLiteralRef
	 *     Comparison.GreaterEq_1_0_0_0 returns EnumLiteralRef
	 *     Comparison.LessEq_1_0_1_0 returns EnumLiteralRef
	 *     Comparison.Greater_1_0_2_0 returns EnumLiteralRef
	 *     Comparison.Less_1_0_3_0 returns EnumLiteralRef
	 *     PlusOrMinus returns EnumLiteralRef
	 *     PlusOrMinus.Plus_1_0_0_0 returns EnumLiteralRef
	 *     PlusOrMinus.Minus_1_0_1_0 returns EnumLiteralRef
	 *     MulOrDiv returns EnumLiteralRef
	 *     MulOrDiv.Multiply_1_0_0_0 returns EnumLiteralRef
	 *     MulOrDiv.Divide_1_0_1_0 returns EnumLiteralRef
	 *     Operator returns EnumLiteralRef
	 *     Primary returns EnumLiteralRef
	 *     Atomic returns EnumLiteralRef
	 *
	 * Constraint:
	 *     literal=[EnumerationLiteral|FQN]
	 * </pre>
	 */
	protected void sequence_Atomic(ISerializationContext context, EnumLiteralRef semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, formulaKPIPackage.Literals.ENUM_LITERAL_REF__LITERAL) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, formulaKPIPackage.Literals.ENUM_LITERAL_REF__LITERAL));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getAtomicAccess().getLiteralEnumerationLiteralFQNTerminalRuleCall_6_1_0_1(), semanticObject.eGet(formulaKPIPackage.Literals.ENUM_LITERAL_REF__LITERAL, false));
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     TopLevelExpression returns IntConstant
	 *     Expression returns IntConstant
	 *     Or returns IntConstant
	 *     Or.Or_1_0 returns IntConstant
	 *     And returns IntConstant
	 *     And.And_1_0 returns IntConstant
	 *     Equality returns IntConstant
	 *     Equality.Equality_1_0_0_0 returns IntConstant
	 *     Equality.Inequality_1_0_1_0 returns IntConstant
	 *     Comparison returns IntConstant
	 *     Comparison.GreaterEq_1_0_0_0 returns IntConstant
	 *     Comparison.LessEq_1_0_1_0 returns IntConstant
	 *     Comparison.Greater_1_0_2_0 returns IntConstant
	 *     Comparison.Less_1_0_3_0 returns IntConstant
	 *     PlusOrMinus returns IntConstant
	 *     PlusOrMinus.Plus_1_0_0_0 returns IntConstant
	 *     PlusOrMinus.Minus_1_0_1_0 returns IntConstant
	 *     MulOrDiv returns IntConstant
	 *     MulOrDiv.Multiply_1_0_0_0 returns IntConstant
	 *     MulOrDiv.Divide_1_0_1_0 returns IntConstant
	 *     Operator returns IntConstant
	 *     Primary returns IntConstant
	 *     Atomic returns IntConstant
	 *
	 * Constraint:
	 *     value=INT
	 * </pre>
	 */
	protected void sequence_Atomic(ISerializationContext context, IntConstant semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, formulaKPIPackage.Literals.INT_CONSTANT__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, formulaKPIPackage.Literals.INT_CONSTANT__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getAtomicAccess().getValueINTTerminalRuleCall_1_1_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     TopLevelExpression returns RealConstant
	 *     Expression returns RealConstant
	 *     Or returns RealConstant
	 *     Or.Or_1_0 returns RealConstant
	 *     And returns RealConstant
	 *     And.And_1_0 returns RealConstant
	 *     Equality returns RealConstant
	 *     Equality.Equality_1_0_0_0 returns RealConstant
	 *     Equality.Inequality_1_0_1_0 returns RealConstant
	 *     Comparison returns RealConstant
	 *     Comparison.GreaterEq_1_0_0_0 returns RealConstant
	 *     Comparison.LessEq_1_0_1_0 returns RealConstant
	 *     Comparison.Greater_1_0_2_0 returns RealConstant
	 *     Comparison.Less_1_0_3_0 returns RealConstant
	 *     PlusOrMinus returns RealConstant
	 *     PlusOrMinus.Plus_1_0_0_0 returns RealConstant
	 *     PlusOrMinus.Minus_1_0_1_0 returns RealConstant
	 *     MulOrDiv returns RealConstant
	 *     MulOrDiv.Multiply_1_0_0_0 returns RealConstant
	 *     MulOrDiv.Divide_1_0_1_0 returns RealConstant
	 *     Operator returns RealConstant
	 *     Primary returns RealConstant
	 *     Atomic returns RealConstant
	 *
	 * Constraint:
	 *     value=DOUBLE
	 * </pre>
	 */
	protected void sequence_Atomic(ISerializationContext context, RealConstant semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, formulaKPIPackage.Literals.REAL_CONSTANT__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, formulaKPIPackage.Literals.REAL_CONSTANT__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getAtomicAccess().getValueDOUBLETerminalRuleCall_2_1_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     TopLevelExpression returns TextConstant
	 *     Expression returns TextConstant
	 *     Or returns TextConstant
	 *     Or.Or_1_0 returns TextConstant
	 *     And returns TextConstant
	 *     And.And_1_0 returns TextConstant
	 *     Equality returns TextConstant
	 *     Equality.Equality_1_0_0_0 returns TextConstant
	 *     Equality.Inequality_1_0_1_0 returns TextConstant
	 *     Comparison returns TextConstant
	 *     Comparison.GreaterEq_1_0_0_0 returns TextConstant
	 *     Comparison.LessEq_1_0_1_0 returns TextConstant
	 *     Comparison.Greater_1_0_2_0 returns TextConstant
	 *     Comparison.Less_1_0_3_0 returns TextConstant
	 *     PlusOrMinus returns TextConstant
	 *     PlusOrMinus.Plus_1_0_0_0 returns TextConstant
	 *     PlusOrMinus.Minus_1_0_1_0 returns TextConstant
	 *     MulOrDiv returns TextConstant
	 *     MulOrDiv.Multiply_1_0_0_0 returns TextConstant
	 *     MulOrDiv.Divide_1_0_1_0 returns TextConstant
	 *     Operator returns TextConstant
	 *     Primary returns TextConstant
	 *     Atomic returns TextConstant
	 *
	 * Constraint:
	 *     value=STRING
	 * </pre>
	 */
	protected void sequence_Atomic(ISerializationContext context, TextConstant semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, formulaKPIPackage.Literals.TEXT_CONSTANT__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, formulaKPIPackage.Literals.TEXT_CONSTANT__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getAtomicAccess().getValueSTRINGTerminalRuleCall_3_1_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     TopLevelExpression returns UnitConstant
	 *     Expression returns UnitConstant
	 *     Or returns UnitConstant
	 *     Or.Or_1_0 returns UnitConstant
	 *     And returns UnitConstant
	 *     And.And_1_0 returns UnitConstant
	 *     Equality returns UnitConstant
	 *     Equality.Equality_1_0_0_0 returns UnitConstant
	 *     Equality.Inequality_1_0_1_0 returns UnitConstant
	 *     Comparison returns UnitConstant
	 *     Comparison.GreaterEq_1_0_0_0 returns UnitConstant
	 *     Comparison.LessEq_1_0_1_0 returns UnitConstant
	 *     Comparison.Greater_1_0_2_0 returns UnitConstant
	 *     Comparison.Less_1_0_3_0 returns UnitConstant
	 *     PlusOrMinus returns UnitConstant
	 *     PlusOrMinus.Plus_1_0_0_0 returns UnitConstant
	 *     PlusOrMinus.Minus_1_0_1_0 returns UnitConstant
	 *     MulOrDiv returns UnitConstant
	 *     MulOrDiv.Multiply_1_0_0_0 returns UnitConstant
	 *     MulOrDiv.Divide_1_0_1_0 returns UnitConstant
	 *     Operator returns UnitConstant
	 *     Primary returns UnitConstant
	 *     Atomic returns UnitConstant
	 *
	 * Constraint:
	 *     (value=DOUBLE unit=ValueUnit)
	 * </pre>
	 */
	protected void sequence_Atomic(ISerializationContext context, UnitConstant semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, formulaKPIPackage.Literals.UNIT_CONSTANT__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, formulaKPIPackage.Literals.UNIT_CONSTANT__VALUE));
			if (transientValues.isValueTransient(semanticObject, formulaKPIPackage.Literals.UNIT_CONSTANT__UNIT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, formulaKPIPackage.Literals.UNIT_CONSTANT__UNIT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getAtomicAccess().getValueDOUBLETerminalRuleCall_5_1_0(), semanticObject.getValue());
		feeder.accept(grammarAccess.getAtomicAccess().getUnitValueUnitEnumRuleCall_5_2_0(), semanticObject.getUnit());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Operation returns Average
	 *     Average returns Average
	 *
	 * Constraint:
	 *     {Average}
	 * </pre>
	 */
	protected void sequence_Average(ISerializationContext context, Average semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     ValueType returns BooleanValue
	 *     BooleanValue returns BooleanValue
	 *
	 * Constraint:
	 *     {BooleanValue}
	 * </pre>
	 */
	protected void sequence_BooleanValue(ISerializationContext context, BooleanValue semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     TopLevelExpression returns Greater
	 *     Expression returns Greater
	 *     Or returns Greater
	 *     Or.Or_1_0 returns Greater
	 *     And returns Greater
	 *     And.And_1_0 returns Greater
	 *     Equality returns Greater
	 *     Equality.Equality_1_0_0_0 returns Greater
	 *     Equality.Inequality_1_0_1_0 returns Greater
	 *     Comparison returns Greater
	 *     Comparison.GreaterEq_1_0_0_0 returns Greater
	 *     Comparison.LessEq_1_0_1_0 returns Greater
	 *     Comparison.Greater_1_0_2_0 returns Greater
	 *     Comparison.Less_1_0_3_0 returns Greater
	 *     PlusOrMinus returns Greater
	 *     PlusOrMinus.Plus_1_0_0_0 returns Greater
	 *     PlusOrMinus.Minus_1_0_1_0 returns Greater
	 *     MulOrDiv returns Greater
	 *     MulOrDiv.Multiply_1_0_0_0 returns Greater
	 *     MulOrDiv.Divide_1_0_1_0 returns Greater
	 *     Operator returns Greater
	 *     Primary returns Greater
	 *
	 * Constraint:
	 *     (left=Comparison_Greater_1_0_2_0 right=PlusOrMinus)
	 * </pre>
	 */
	protected void sequence_Comparison(ISerializationContext context, Greater semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, formulaKPIPackage.Literals.BIN_OP__LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, formulaKPIPackage.Literals.BIN_OP__LEFT));
			if (transientValues.isValueTransient(semanticObject, formulaKPIPackage.Literals.BIN_OP__RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, formulaKPIPackage.Literals.BIN_OP__RIGHT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getComparisonAccess().getGreaterLeftAction_1_0_2_0(), semanticObject.getLeft());
		feeder.accept(grammarAccess.getComparisonAccess().getRightPlusOrMinusParserRuleCall_1_1_0(), semanticObject.getRight());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     TopLevelExpression returns GreaterEq
	 *     Expression returns GreaterEq
	 *     Or returns GreaterEq
	 *     Or.Or_1_0 returns GreaterEq
	 *     And returns GreaterEq
	 *     And.And_1_0 returns GreaterEq
	 *     Equality returns GreaterEq
	 *     Equality.Equality_1_0_0_0 returns GreaterEq
	 *     Equality.Inequality_1_0_1_0 returns GreaterEq
	 *     Comparison returns GreaterEq
	 *     Comparison.GreaterEq_1_0_0_0 returns GreaterEq
	 *     Comparison.LessEq_1_0_1_0 returns GreaterEq
	 *     Comparison.Greater_1_0_2_0 returns GreaterEq
	 *     Comparison.Less_1_0_3_0 returns GreaterEq
	 *     PlusOrMinus returns GreaterEq
	 *     PlusOrMinus.Plus_1_0_0_0 returns GreaterEq
	 *     PlusOrMinus.Minus_1_0_1_0 returns GreaterEq
	 *     MulOrDiv returns GreaterEq
	 *     MulOrDiv.Multiply_1_0_0_0 returns GreaterEq
	 *     MulOrDiv.Divide_1_0_1_0 returns GreaterEq
	 *     Operator returns GreaterEq
	 *     Primary returns GreaterEq
	 *
	 * Constraint:
	 *     (left=Comparison_GreaterEq_1_0_0_0 right=PlusOrMinus)
	 * </pre>
	 */
	protected void sequence_Comparison(ISerializationContext context, GreaterEq semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, formulaKPIPackage.Literals.BIN_OP__LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, formulaKPIPackage.Literals.BIN_OP__LEFT));
			if (transientValues.isValueTransient(semanticObject, formulaKPIPackage.Literals.BIN_OP__RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, formulaKPIPackage.Literals.BIN_OP__RIGHT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getComparisonAccess().getGreaterEqLeftAction_1_0_0_0(), semanticObject.getLeft());
		feeder.accept(grammarAccess.getComparisonAccess().getRightPlusOrMinusParserRuleCall_1_1_0(), semanticObject.getRight());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     TopLevelExpression returns Less
	 *     Expression returns Less
	 *     Or returns Less
	 *     Or.Or_1_0 returns Less
	 *     And returns Less
	 *     And.And_1_0 returns Less
	 *     Equality returns Less
	 *     Equality.Equality_1_0_0_0 returns Less
	 *     Equality.Inequality_1_0_1_0 returns Less
	 *     Comparison returns Less
	 *     Comparison.GreaterEq_1_0_0_0 returns Less
	 *     Comparison.LessEq_1_0_1_0 returns Less
	 *     Comparison.Greater_1_0_2_0 returns Less
	 *     Comparison.Less_1_0_3_0 returns Less
	 *     PlusOrMinus returns Less
	 *     PlusOrMinus.Plus_1_0_0_0 returns Less
	 *     PlusOrMinus.Minus_1_0_1_0 returns Less
	 *     MulOrDiv returns Less
	 *     MulOrDiv.Multiply_1_0_0_0 returns Less
	 *     MulOrDiv.Divide_1_0_1_0 returns Less
	 *     Operator returns Less
	 *     Primary returns Less
	 *
	 * Constraint:
	 *     (left=Comparison_Less_1_0_3_0 right=PlusOrMinus)
	 * </pre>
	 */
	protected void sequence_Comparison(ISerializationContext context, Less semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, formulaKPIPackage.Literals.BIN_OP__LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, formulaKPIPackage.Literals.BIN_OP__LEFT));
			if (transientValues.isValueTransient(semanticObject, formulaKPIPackage.Literals.BIN_OP__RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, formulaKPIPackage.Literals.BIN_OP__RIGHT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getComparisonAccess().getLessLeftAction_1_0_3_0(), semanticObject.getLeft());
		feeder.accept(grammarAccess.getComparisonAccess().getRightPlusOrMinusParserRuleCall_1_1_0(), semanticObject.getRight());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     TopLevelExpression returns LessEq
	 *     Expression returns LessEq
	 *     Or returns LessEq
	 *     Or.Or_1_0 returns LessEq
	 *     And returns LessEq
	 *     And.And_1_0 returns LessEq
	 *     Equality returns LessEq
	 *     Equality.Equality_1_0_0_0 returns LessEq
	 *     Equality.Inequality_1_0_1_0 returns LessEq
	 *     Comparison returns LessEq
	 *     Comparison.GreaterEq_1_0_0_0 returns LessEq
	 *     Comparison.LessEq_1_0_1_0 returns LessEq
	 *     Comparison.Greater_1_0_2_0 returns LessEq
	 *     Comparison.Less_1_0_3_0 returns LessEq
	 *     PlusOrMinus returns LessEq
	 *     PlusOrMinus.Plus_1_0_0_0 returns LessEq
	 *     PlusOrMinus.Minus_1_0_1_0 returns LessEq
	 *     MulOrDiv returns LessEq
	 *     MulOrDiv.Multiply_1_0_0_0 returns LessEq
	 *     MulOrDiv.Divide_1_0_1_0 returns LessEq
	 *     Operator returns LessEq
	 *     Primary returns LessEq
	 *
	 * Constraint:
	 *     (left=Comparison_LessEq_1_0_1_0 right=PlusOrMinus)
	 * </pre>
	 */
	protected void sequence_Comparison(ISerializationContext context, LessEq semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, formulaKPIPackage.Literals.BIN_OP__LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, formulaKPIPackage.Literals.BIN_OP__LEFT));
			if (transientValues.isValueTransient(semanticObject, formulaKPIPackage.Literals.BIN_OP__RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, formulaKPIPackage.Literals.BIN_OP__RIGHT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getComparisonAccess().getLessEqLeftAction_1_0_1_0(), semanticObject.getLeft());
		feeder.accept(grammarAccess.getComparisonAccess().getRightPlusOrMinusParserRuleCall_1_1_0(), semanticObject.getRight());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Computation returns Computation
	 *
	 * Constraint:
	 *     (computed=[Computable|ID] formula=TopLevelExpression)
	 * </pre>
	 */
	protected void sequence_Computation(ISerializationContext context, Computation semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, formulaKPIPackage.Literals.COMPUTATION__COMPUTED) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, formulaKPIPackage.Literals.COMPUTATION__COMPUTED));
			if (transientValues.isValueTransient(semanticObject, formulaKPIPackage.Literals.COMPUTATION__FORMULA) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, formulaKPIPackage.Literals.COMPUTATION__FORMULA));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getComputationAccess().getComputedComputableIDTerminalRuleCall_0_0_1(), semanticObject.eGet(formulaKPIPackage.Literals.COMPUTATION__COMPUTED, false));
		feeder.accept(grammarAccess.getComputationAccess().getFormulaTopLevelExpressionParserRuleCall_2_0(), semanticObject.getFormula());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     TopLevelExpression returns ConditionalOp
	 *     Condition returns ConditionalOp
	 *
	 * Constraint:
	 *     ((conditions+=Expression results+=Expression)+ results+=Expression)
	 * </pre>
	 */
	protected void sequence_Condition(ISerializationContext context, ConditionalOp semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Declaration returns Declaration
	 *
	 * Constraint:
	 *     declared=Declarable
	 * </pre>
	 */
	protected void sequence_Declaration(ISerializationContext context, Declaration semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, formulaKPIPackage.Literals.DECLARATION__DECLARED) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, formulaKPIPackage.Literals.DECLARATION__DECLARED));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getDeclarationAccess().getDeclaredDeclarableParserRuleCall_0(), semanticObject.getDeclared());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     ValueType returns DriftValue
	 *     DriftValue returns DriftValue
	 *
	 * Constraint:
	 *     (operation=Operation window=INT windowUnit=WindowUnit)
	 * </pre>
	 */
	protected void sequence_DriftValue(ISerializationContext context, DriftValue semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, formulaKPIPackage.Literals.DRIFT_VALUE__OPERATION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, formulaKPIPackage.Literals.DRIFT_VALUE__OPERATION));
			if (transientValues.isValueTransient(semanticObject, formulaKPIPackage.Literals.DRIFT_VALUE__WINDOW) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, formulaKPIPackage.Literals.DRIFT_VALUE__WINDOW));
			if (transientValues.isValueTransient(semanticObject, formulaKPIPackage.Literals.DRIFT_VALUE__WINDOW_UNIT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, formulaKPIPackage.Literals.DRIFT_VALUE__WINDOW_UNIT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getDriftValueAccess().getOperationOperationParserRuleCall_2_0(), semanticObject.getOperation());
		feeder.accept(grammarAccess.getDriftValueAccess().getWindowINTTerminalRuleCall_4_0(), semanticObject.getWindow());
		feeder.accept(grammarAccess.getDriftValueAccess().getWindowUnitWindowUnitEnumRuleCall_5_0(), semanticObject.getWindowUnit());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     EnumerationLiteral returns EnumerationLiteral
	 *
	 * Constraint:
	 *     name=ID
	 * </pre>
	 */
	protected void sequence_EnumerationLiteral(ISerializationContext context, EnumerationLiteral semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, formulaKPIPackage.Literals.ENUMERATION_LITERAL__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, formulaKPIPackage.Literals.ENUMERATION_LITERAL__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getEnumerationLiteralAccess().getNameIDTerminalRuleCall_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     ValueType returns EnumerationValue
	 *     EnumerationValue returns EnumerationValue
	 *
	 * Constraint:
	 *     literals+=EnumerationLiteral+
	 * </pre>
	 */
	protected void sequence_EnumerationValue(ISerializationContext context, EnumerationValue semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     TopLevelExpression returns Equality
	 *     Expression returns Equality
	 *     Or returns Equality
	 *     Or.Or_1_0 returns Equality
	 *     And returns Equality
	 *     And.And_1_0 returns Equality
	 *     Equality returns Equality
	 *     Equality.Equality_1_0_0_0 returns Equality
	 *     Equality.Inequality_1_0_1_0 returns Equality
	 *     Comparison returns Equality
	 *     Comparison.GreaterEq_1_0_0_0 returns Equality
	 *     Comparison.LessEq_1_0_1_0 returns Equality
	 *     Comparison.Greater_1_0_2_0 returns Equality
	 *     Comparison.Less_1_0_3_0 returns Equality
	 *     PlusOrMinus returns Equality
	 *     PlusOrMinus.Plus_1_0_0_0 returns Equality
	 *     PlusOrMinus.Minus_1_0_1_0 returns Equality
	 *     MulOrDiv returns Equality
	 *     MulOrDiv.Multiply_1_0_0_0 returns Equality
	 *     MulOrDiv.Divide_1_0_1_0 returns Equality
	 *     Operator returns Equality
	 *     Primary returns Equality
	 *
	 * Constraint:
	 *     (left=Equality_Equality_1_0_0_0 right=Comparison)
	 * </pre>
	 */
	protected void sequence_Equality(ISerializationContext context, Equality semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, formulaKPIPackage.Literals.BIN_OP__LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, formulaKPIPackage.Literals.BIN_OP__LEFT));
			if (transientValues.isValueTransient(semanticObject, formulaKPIPackage.Literals.BIN_OP__RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, formulaKPIPackage.Literals.BIN_OP__RIGHT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getEqualityAccess().getEqualityLeftAction_1_0_0_0(), semanticObject.getLeft());
		feeder.accept(grammarAccess.getEqualityAccess().getRightComparisonParserRuleCall_1_1_0(), semanticObject.getRight());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     TopLevelExpression returns Inequality
	 *     Expression returns Inequality
	 *     Or returns Inequality
	 *     Or.Or_1_0 returns Inequality
	 *     And returns Inequality
	 *     And.And_1_0 returns Inequality
	 *     Equality returns Inequality
	 *     Equality.Equality_1_0_0_0 returns Inequality
	 *     Equality.Inequality_1_0_1_0 returns Inequality
	 *     Comparison returns Inequality
	 *     Comparison.GreaterEq_1_0_0_0 returns Inequality
	 *     Comparison.LessEq_1_0_1_0 returns Inequality
	 *     Comparison.Greater_1_0_2_0 returns Inequality
	 *     Comparison.Less_1_0_3_0 returns Inequality
	 *     PlusOrMinus returns Inequality
	 *     PlusOrMinus.Plus_1_0_0_0 returns Inequality
	 *     PlusOrMinus.Minus_1_0_1_0 returns Inequality
	 *     MulOrDiv returns Inequality
	 *     MulOrDiv.Multiply_1_0_0_0 returns Inequality
	 *     MulOrDiv.Divide_1_0_1_0 returns Inequality
	 *     Operator returns Inequality
	 *     Primary returns Inequality
	 *
	 * Constraint:
	 *     (left=Equality_Inequality_1_0_1_0 right=Comparison)
	 * </pre>
	 */
	protected void sequence_Equality(ISerializationContext context, Inequality semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, formulaKPIPackage.Literals.BIN_OP__LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, formulaKPIPackage.Literals.BIN_OP__LEFT));
			if (transientValues.isValueTransient(semanticObject, formulaKPIPackage.Literals.BIN_OP__RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, formulaKPIPackage.Literals.BIN_OP__RIGHT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getEqualityAccess().getInequalityLeftAction_1_0_1_0(), semanticObject.getLeft());
		feeder.accept(grammarAccess.getEqualityAccess().getRightComparisonParserRuleCall_1_1_0(), semanticObject.getRight());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     ValueType returns IntegerValue
	 *     IntegerValue returns IntegerValue
	 *
	 * Constraint:
	 *     {IntegerValue}
	 * </pre>
	 */
	protected void sequence_IntegerValue(ISerializationContext context, IntegerValue semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     KPIFormulaDSL returns KPIFormula
	 *
	 * Constraint:
	 *     (declarations+=Declaration | computations+=Computation)+
	 * </pre>
	 */
	protected void sequence_KPIFormulaDSL(ISerializationContext context, KPIFormula semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Declarable returns KPI
	 *     KPI returns KPI
	 *
	 * Constraint:
	 *     (name=ID type=ValueType)
	 * </pre>
	 */
	protected void sequence_KPI(ISerializationContext context, KPI semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, formulaKPIPackage.Literals.COMPUTABLE__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, formulaKPIPackage.Literals.COMPUTABLE__NAME));
			if (transientValues.isValueTransient(semanticObject, formulaKPIPackage.Literals.DECLARABLE__TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, formulaKPIPackage.Literals.DECLARABLE__TYPE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getKPIAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getKPIAccess().getTypeValueTypeParserRuleCall_4_0(), semanticObject.getType());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     ListIterator returns ListIterator
	 *
	 * Constraint:
	 *     name=ID
	 * </pre>
	 */
	protected void sequence_ListIterator(ISerializationContext context, ListIterator semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, formulaKPIPackage.Literals.COMPUTABLE__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, formulaKPIPackage.Literals.COMPUTABLE__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getListIteratorAccess().getNameIDTerminalRuleCall_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Operation returns Maximum
	 *     Maximum returns Maximum
	 *
	 * Constraint:
	 *     {Maximum}
	 * </pre>
	 */
	protected void sequence_Maximum(ISerializationContext context, Maximum semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Operation returns Median
	 *     Median returns Median
	 *
	 * Constraint:
	 *     {Median}
	 * </pre>
	 */
	protected void sequence_Median(ISerializationContext context, Median semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Declarable returns Metric
	 *     Metric returns Metric
	 *
	 * Constraint:
	 *     (name=ID type=ValueType)
	 * </pre>
	 */
	protected void sequence_Metric(ISerializationContext context, Metric semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, formulaKPIPackage.Literals.COMPUTABLE__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, formulaKPIPackage.Literals.COMPUTABLE__NAME));
			if (transientValues.isValueTransient(semanticObject, formulaKPIPackage.Literals.DECLARABLE__TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, formulaKPIPackage.Literals.DECLARABLE__TYPE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getMetricAccess().getNameIDTerminalRuleCall_0_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getMetricAccess().getTypeValueTypeParserRuleCall_3_0(), semanticObject.getType());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Operation returns Minimum
	 *     Minimum returns Minimum
	 *
	 * Constraint:
	 *     {Minimum}
	 * </pre>
	 */
	protected void sequence_Minimum(ISerializationContext context, Minimum semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     TopLevelExpression returns Divide
	 *     Expression returns Divide
	 *     Or returns Divide
	 *     Or.Or_1_0 returns Divide
	 *     And returns Divide
	 *     And.And_1_0 returns Divide
	 *     Equality returns Divide
	 *     Equality.Equality_1_0_0_0 returns Divide
	 *     Equality.Inequality_1_0_1_0 returns Divide
	 *     Comparison returns Divide
	 *     Comparison.GreaterEq_1_0_0_0 returns Divide
	 *     Comparison.LessEq_1_0_1_0 returns Divide
	 *     Comparison.Greater_1_0_2_0 returns Divide
	 *     Comparison.Less_1_0_3_0 returns Divide
	 *     PlusOrMinus returns Divide
	 *     PlusOrMinus.Plus_1_0_0_0 returns Divide
	 *     PlusOrMinus.Minus_1_0_1_0 returns Divide
	 *     MulOrDiv returns Divide
	 *     MulOrDiv.Multiply_1_0_0_0 returns Divide
	 *     MulOrDiv.Divide_1_0_1_0 returns Divide
	 *     Operator returns Divide
	 *     Primary returns Divide
	 *
	 * Constraint:
	 *     (left=MulOrDiv_Divide_1_0_1_0 right=Operator)
	 * </pre>
	 */
	protected void sequence_MulOrDiv(ISerializationContext context, Divide semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, formulaKPIPackage.Literals.BIN_OP__LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, formulaKPIPackage.Literals.BIN_OP__LEFT));
			if (transientValues.isValueTransient(semanticObject, formulaKPIPackage.Literals.BIN_OP__RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, formulaKPIPackage.Literals.BIN_OP__RIGHT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getMulOrDivAccess().getDivideLeftAction_1_0_1_0(), semanticObject.getLeft());
		feeder.accept(grammarAccess.getMulOrDivAccess().getRightOperatorParserRuleCall_1_1_0(), semanticObject.getRight());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     TopLevelExpression returns Multiply
	 *     Expression returns Multiply
	 *     Or returns Multiply
	 *     Or.Or_1_0 returns Multiply
	 *     And returns Multiply
	 *     And.And_1_0 returns Multiply
	 *     Equality returns Multiply
	 *     Equality.Equality_1_0_0_0 returns Multiply
	 *     Equality.Inequality_1_0_1_0 returns Multiply
	 *     Comparison returns Multiply
	 *     Comparison.GreaterEq_1_0_0_0 returns Multiply
	 *     Comparison.LessEq_1_0_1_0 returns Multiply
	 *     Comparison.Greater_1_0_2_0 returns Multiply
	 *     Comparison.Less_1_0_3_0 returns Multiply
	 *     PlusOrMinus returns Multiply
	 *     PlusOrMinus.Plus_1_0_0_0 returns Multiply
	 *     PlusOrMinus.Minus_1_0_1_0 returns Multiply
	 *     MulOrDiv returns Multiply
	 *     MulOrDiv.Multiply_1_0_0_0 returns Multiply
	 *     MulOrDiv.Divide_1_0_1_0 returns Multiply
	 *     Operator returns Multiply
	 *     Primary returns Multiply
	 *
	 * Constraint:
	 *     (left=MulOrDiv_Multiply_1_0_0_0 right=Operator)
	 * </pre>
	 */
	protected void sequence_MulOrDiv(ISerializationContext context, Multiply semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, formulaKPIPackage.Literals.BIN_OP__LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, formulaKPIPackage.Literals.BIN_OP__LEFT));
			if (transientValues.isValueTransient(semanticObject, formulaKPIPackage.Literals.BIN_OP__RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, formulaKPIPackage.Literals.BIN_OP__RIGHT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getMulOrDivAccess().getMultiplyLeftAction_1_0_0_0(), semanticObject.getLeft());
		feeder.accept(grammarAccess.getMulOrDivAccess().getRightOperatorParserRuleCall_1_1_0(), semanticObject.getRight());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     TopLevelExpression returns AvgOp
	 *     Expression returns AvgOp
	 *     Or returns AvgOp
	 *     Or.Or_1_0 returns AvgOp
	 *     And returns AvgOp
	 *     And.And_1_0 returns AvgOp
	 *     Equality returns AvgOp
	 *     Equality.Equality_1_0_0_0 returns AvgOp
	 *     Equality.Inequality_1_0_1_0 returns AvgOp
	 *     Comparison returns AvgOp
	 *     Comparison.GreaterEq_1_0_0_0 returns AvgOp
	 *     Comparison.LessEq_1_0_1_0 returns AvgOp
	 *     Comparison.Greater_1_0_2_0 returns AvgOp
	 *     Comparison.Less_1_0_3_0 returns AvgOp
	 *     PlusOrMinus returns AvgOp
	 *     PlusOrMinus.Plus_1_0_0_0 returns AvgOp
	 *     PlusOrMinus.Minus_1_0_1_0 returns AvgOp
	 *     MulOrDiv returns AvgOp
	 *     MulOrDiv.Multiply_1_0_0_0 returns AvgOp
	 *     MulOrDiv.Divide_1_0_1_0 returns AvgOp
	 *     Operator returns AvgOp
	 *     Primary returns AvgOp
	 *
	 * Constraint:
	 *     list=Expression
	 * </pre>
	 */
	protected void sequence_Operator(ISerializationContext context, AvgOp semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, formulaKPIPackage.Literals.AVG_OP__LIST) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, formulaKPIPackage.Literals.AVG_OP__LIST));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getOperatorAccess().getListExpressionParserRuleCall_2_3_0(), semanticObject.getList());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     TopLevelExpression returns ListFilter
	 *     Expression returns ListFilter
	 *     Or returns ListFilter
	 *     Or.Or_1_0 returns ListFilter
	 *     And returns ListFilter
	 *     And.And_1_0 returns ListFilter
	 *     Equality returns ListFilter
	 *     Equality.Equality_1_0_0_0 returns ListFilter
	 *     Equality.Inequality_1_0_1_0 returns ListFilter
	 *     Comparison returns ListFilter
	 *     Comparison.GreaterEq_1_0_0_0 returns ListFilter
	 *     Comparison.LessEq_1_0_1_0 returns ListFilter
	 *     Comparison.Greater_1_0_2_0 returns ListFilter
	 *     Comparison.Less_1_0_3_0 returns ListFilter
	 *     PlusOrMinus returns ListFilter
	 *     PlusOrMinus.Plus_1_0_0_0 returns ListFilter
	 *     PlusOrMinus.Minus_1_0_1_0 returns ListFilter
	 *     MulOrDiv returns ListFilter
	 *     MulOrDiv.Multiply_1_0_0_0 returns ListFilter
	 *     MulOrDiv.Divide_1_0_1_0 returns ListFilter
	 *     Operator returns ListFilter
	 *     Primary returns ListFilter
	 *
	 * Constraint:
	 *     (expression=TopLevelExpression iterators+=ListIterator lists+=Primary (iterators+=ListIterator lists+=Primary)*)
	 * </pre>
	 */
	protected void sequence_Operator(ISerializationContext context, ListFilter semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     TopLevelExpression returns ListIteration
	 *     Expression returns ListIteration
	 *     Or returns ListIteration
	 *     Or.Or_1_0 returns ListIteration
	 *     And returns ListIteration
	 *     And.And_1_0 returns ListIteration
	 *     Equality returns ListIteration
	 *     Equality.Equality_1_0_0_0 returns ListIteration
	 *     Equality.Inequality_1_0_1_0 returns ListIteration
	 *     Comparison returns ListIteration
	 *     Comparison.GreaterEq_1_0_0_0 returns ListIteration
	 *     Comparison.LessEq_1_0_1_0 returns ListIteration
	 *     Comparison.Greater_1_0_2_0 returns ListIteration
	 *     Comparison.Less_1_0_3_0 returns ListIteration
	 *     PlusOrMinus returns ListIteration
	 *     PlusOrMinus.Plus_1_0_0_0 returns ListIteration
	 *     PlusOrMinus.Minus_1_0_1_0 returns ListIteration
	 *     MulOrDiv returns ListIteration
	 *     MulOrDiv.Multiply_1_0_0_0 returns ListIteration
	 *     MulOrDiv.Divide_1_0_1_0 returns ListIteration
	 *     Operator returns ListIteration
	 *     Primary returns ListIteration
	 *
	 * Constraint:
	 *     (expression=TopLevelExpression iterators+=ListIterator lists+=Primary (iterators+=ListIterator lists+=Primary)*)
	 * </pre>
	 */
	protected void sequence_Operator(ISerializationContext context, ListIteration semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     TopLevelExpression returns ListLiteral
	 *     Expression returns ListLiteral
	 *     Or returns ListLiteral
	 *     Or.Or_1_0 returns ListLiteral
	 *     And returns ListLiteral
	 *     And.And_1_0 returns ListLiteral
	 *     Equality returns ListLiteral
	 *     Equality.Equality_1_0_0_0 returns ListLiteral
	 *     Equality.Inequality_1_0_1_0 returns ListLiteral
	 *     Comparison returns ListLiteral
	 *     Comparison.GreaterEq_1_0_0_0 returns ListLiteral
	 *     Comparison.LessEq_1_0_1_0 returns ListLiteral
	 *     Comparison.Greater_1_0_2_0 returns ListLiteral
	 *     Comparison.Less_1_0_3_0 returns ListLiteral
	 *     PlusOrMinus returns ListLiteral
	 *     PlusOrMinus.Plus_1_0_0_0 returns ListLiteral
	 *     PlusOrMinus.Minus_1_0_1_0 returns ListLiteral
	 *     MulOrDiv returns ListLiteral
	 *     MulOrDiv.Multiply_1_0_0_0 returns ListLiteral
	 *     MulOrDiv.Divide_1_0_1_0 returns ListLiteral
	 *     Operator returns ListLiteral
	 *     Primary returns ListLiteral
	 *
	 * Constraint:
	 *     (elements+=Expression elements+=Expression*)
	 * </pre>
	 */
	protected void sequence_Operator(ISerializationContext context, ListLiteral semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     TopLevelExpression returns ListReduce
	 *     Expression returns ListReduce
	 *     Or returns ListReduce
	 *     Or.Or_1_0 returns ListReduce
	 *     And returns ListReduce
	 *     And.And_1_0 returns ListReduce
	 *     Equality returns ListReduce
	 *     Equality.Equality_1_0_0_0 returns ListReduce
	 *     Equality.Inequality_1_0_1_0 returns ListReduce
	 *     Comparison returns ListReduce
	 *     Comparison.GreaterEq_1_0_0_0 returns ListReduce
	 *     Comparison.LessEq_1_0_1_0 returns ListReduce
	 *     Comparison.Greater_1_0_2_0 returns ListReduce
	 *     Comparison.Less_1_0_3_0 returns ListReduce
	 *     PlusOrMinus returns ListReduce
	 *     PlusOrMinus.Plus_1_0_0_0 returns ListReduce
	 *     PlusOrMinus.Minus_1_0_1_0 returns ListReduce
	 *     MulOrDiv returns ListReduce
	 *     MulOrDiv.Multiply_1_0_0_0 returns ListReduce
	 *     MulOrDiv.Divide_1_0_1_0 returns ListReduce
	 *     Operator returns ListReduce
	 *     Primary returns ListReduce
	 *
	 * Constraint:
	 *     (expression=TopLevelExpression accumulator=Primary iterators+=ListIterator lists+=Primary (iterators+=ListIterator lists+=Primary)*)
	 * </pre>
	 */
	protected void sequence_Operator(ISerializationContext context, ListReduce semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     TopLevelExpression returns ListSize
	 *     Expression returns ListSize
	 *     Or returns ListSize
	 *     Or.Or_1_0 returns ListSize
	 *     And returns ListSize
	 *     And.And_1_0 returns ListSize
	 *     Equality returns ListSize
	 *     Equality.Equality_1_0_0_0 returns ListSize
	 *     Equality.Inequality_1_0_1_0 returns ListSize
	 *     Comparison returns ListSize
	 *     Comparison.GreaterEq_1_0_0_0 returns ListSize
	 *     Comparison.LessEq_1_0_1_0 returns ListSize
	 *     Comparison.Greater_1_0_2_0 returns ListSize
	 *     Comparison.Less_1_0_3_0 returns ListSize
	 *     PlusOrMinus returns ListSize
	 *     PlusOrMinus.Plus_1_0_0_0 returns ListSize
	 *     PlusOrMinus.Minus_1_0_1_0 returns ListSize
	 *     MulOrDiv returns ListSize
	 *     MulOrDiv.Multiply_1_0_0_0 returns ListSize
	 *     MulOrDiv.Divide_1_0_1_0 returns ListSize
	 *     Operator returns ListSize
	 *     Primary returns ListSize
	 *
	 * Constraint:
	 *     expression=Expression
	 * </pre>
	 */
	protected void sequence_Operator(ISerializationContext context, ListSize semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, formulaKPIPackage.Literals.LIST_SIZE__EXPRESSION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, formulaKPIPackage.Literals.LIST_SIZE__EXPRESSION));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getOperatorAccess().getExpressionExpressionParserRuleCall_0_2_0(), semanticObject.getExpression());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     TopLevelExpression returns MaxOp
	 *     Expression returns MaxOp
	 *     Or returns MaxOp
	 *     Or.Or_1_0 returns MaxOp
	 *     And returns MaxOp
	 *     And.And_1_0 returns MaxOp
	 *     Equality returns MaxOp
	 *     Equality.Equality_1_0_0_0 returns MaxOp
	 *     Equality.Inequality_1_0_1_0 returns MaxOp
	 *     Comparison returns MaxOp
	 *     Comparison.GreaterEq_1_0_0_0 returns MaxOp
	 *     Comparison.LessEq_1_0_1_0 returns MaxOp
	 *     Comparison.Greater_1_0_2_0 returns MaxOp
	 *     Comparison.Less_1_0_3_0 returns MaxOp
	 *     PlusOrMinus returns MaxOp
	 *     PlusOrMinus.Plus_1_0_0_0 returns MaxOp
	 *     PlusOrMinus.Minus_1_0_1_0 returns MaxOp
	 *     MulOrDiv returns MaxOp
	 *     MulOrDiv.Multiply_1_0_0_0 returns MaxOp
	 *     MulOrDiv.Divide_1_0_1_0 returns MaxOp
	 *     Operator returns MaxOp
	 *     Primary returns MaxOp
	 *
	 * Constraint:
	 *     list=Expression
	 * </pre>
	 */
	protected void sequence_Operator(ISerializationContext context, MaxOp semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, formulaKPIPackage.Literals.MAX_OP__LIST) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, formulaKPIPackage.Literals.MAX_OP__LIST));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getOperatorAccess().getListExpressionParserRuleCall_6_3_0(), semanticObject.getList());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     TopLevelExpression returns MinOp
	 *     Expression returns MinOp
	 *     Or returns MinOp
	 *     Or.Or_1_0 returns MinOp
	 *     And returns MinOp
	 *     And.And_1_0 returns MinOp
	 *     Equality returns MinOp
	 *     Equality.Equality_1_0_0_0 returns MinOp
	 *     Equality.Inequality_1_0_1_0 returns MinOp
	 *     Comparison returns MinOp
	 *     Comparison.GreaterEq_1_0_0_0 returns MinOp
	 *     Comparison.LessEq_1_0_1_0 returns MinOp
	 *     Comparison.Greater_1_0_2_0 returns MinOp
	 *     Comparison.Less_1_0_3_0 returns MinOp
	 *     PlusOrMinus returns MinOp
	 *     PlusOrMinus.Plus_1_0_0_0 returns MinOp
	 *     PlusOrMinus.Minus_1_0_1_0 returns MinOp
	 *     MulOrDiv returns MinOp
	 *     MulOrDiv.Multiply_1_0_0_0 returns MinOp
	 *     MulOrDiv.Divide_1_0_1_0 returns MinOp
	 *     Operator returns MinOp
	 *     Primary returns MinOp
	 *
	 * Constraint:
	 *     list=Expression
	 * </pre>
	 */
	protected void sequence_Operator(ISerializationContext context, MinOp semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, formulaKPIPackage.Literals.MIN_OP__LIST) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, formulaKPIPackage.Literals.MIN_OP__LIST));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getOperatorAccess().getListExpressionParserRuleCall_5_3_0(), semanticObject.getList());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     TopLevelExpression returns SumOp
	 *     Expression returns SumOp
	 *     Or returns SumOp
	 *     Or.Or_1_0 returns SumOp
	 *     And returns SumOp
	 *     And.And_1_0 returns SumOp
	 *     Equality returns SumOp
	 *     Equality.Equality_1_0_0_0 returns SumOp
	 *     Equality.Inequality_1_0_1_0 returns SumOp
	 *     Comparison returns SumOp
	 *     Comparison.GreaterEq_1_0_0_0 returns SumOp
	 *     Comparison.LessEq_1_0_1_0 returns SumOp
	 *     Comparison.Greater_1_0_2_0 returns SumOp
	 *     Comparison.Less_1_0_3_0 returns SumOp
	 *     PlusOrMinus returns SumOp
	 *     PlusOrMinus.Plus_1_0_0_0 returns SumOp
	 *     PlusOrMinus.Minus_1_0_1_0 returns SumOp
	 *     MulOrDiv returns SumOp
	 *     MulOrDiv.Multiply_1_0_0_0 returns SumOp
	 *     MulOrDiv.Divide_1_0_1_0 returns SumOp
	 *     Operator returns SumOp
	 *     Primary returns SumOp
	 *
	 * Constraint:
	 *     list=Expression
	 * </pre>
	 */
	protected void sequence_Operator(ISerializationContext context, SumOp semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, formulaKPIPackage.Literals.SUM_OP__LIST) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, formulaKPIPackage.Literals.SUM_OP__LIST));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getOperatorAccess().getListExpressionParserRuleCall_4_3_0(), semanticObject.getList());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     TopLevelExpression returns ThresholdOp
	 *     Expression returns ThresholdOp
	 *     Or returns ThresholdOp
	 *     Or.Or_1_0 returns ThresholdOp
	 *     And returns ThresholdOp
	 *     And.And_1_0 returns ThresholdOp
	 *     Equality returns ThresholdOp
	 *     Equality.Equality_1_0_0_0 returns ThresholdOp
	 *     Equality.Inequality_1_0_1_0 returns ThresholdOp
	 *     Comparison returns ThresholdOp
	 *     Comparison.GreaterEq_1_0_0_0 returns ThresholdOp
	 *     Comparison.LessEq_1_0_1_0 returns ThresholdOp
	 *     Comparison.Greater_1_0_2_0 returns ThresholdOp
	 *     Comparison.Less_1_0_3_0 returns ThresholdOp
	 *     PlusOrMinus returns ThresholdOp
	 *     PlusOrMinus.Plus_1_0_0_0 returns ThresholdOp
	 *     PlusOrMinus.Minus_1_0_1_0 returns ThresholdOp
	 *     MulOrDiv returns ThresholdOp
	 *     MulOrDiv.Multiply_1_0_0_0 returns ThresholdOp
	 *     MulOrDiv.Divide_1_0_1_0 returns ThresholdOp
	 *     Operator returns ThresholdOp
	 *     Primary returns ThresholdOp
	 *
	 * Constraint:
	 *     (expression=Expression threshold=Expression)
	 * </pre>
	 */
	protected void sequence_Operator(ISerializationContext context, ThresholdOp semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, formulaKPIPackage.Literals.THRESHOLD_OP__EXPRESSION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, formulaKPIPackage.Literals.THRESHOLD_OP__EXPRESSION));
			if (transientValues.isValueTransient(semanticObject, formulaKPIPackage.Literals.THRESHOLD_OP__THRESHOLD) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, formulaKPIPackage.Literals.THRESHOLD_OP__THRESHOLD));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getOperatorAccess().getExpressionExpressionParserRuleCall_7_3_0(), semanticObject.getExpression());
		feeder.accept(grammarAccess.getOperatorAccess().getThresholdExpressionParserRuleCall_7_5_0(), semanticObject.getThreshold());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     TopLevelExpression returns WeightedSumOp
	 *     Expression returns WeightedSumOp
	 *     Or returns WeightedSumOp
	 *     Or.Or_1_0 returns WeightedSumOp
	 *     And returns WeightedSumOp
	 *     And.And_1_0 returns WeightedSumOp
	 *     Equality returns WeightedSumOp
	 *     Equality.Equality_1_0_0_0 returns WeightedSumOp
	 *     Equality.Inequality_1_0_1_0 returns WeightedSumOp
	 *     Comparison returns WeightedSumOp
	 *     Comparison.GreaterEq_1_0_0_0 returns WeightedSumOp
	 *     Comparison.LessEq_1_0_1_0 returns WeightedSumOp
	 *     Comparison.Greater_1_0_2_0 returns WeightedSumOp
	 *     Comparison.Less_1_0_3_0 returns WeightedSumOp
	 *     PlusOrMinus returns WeightedSumOp
	 *     PlusOrMinus.Plus_1_0_0_0 returns WeightedSumOp
	 *     PlusOrMinus.Minus_1_0_1_0 returns WeightedSumOp
	 *     MulOrDiv returns WeightedSumOp
	 *     MulOrDiv.Multiply_1_0_0_0 returns WeightedSumOp
	 *     MulOrDiv.Divide_1_0_1_0 returns WeightedSumOp
	 *     Operator returns WeightedSumOp
	 *     Primary returns WeightedSumOp
	 *
	 * Constraint:
	 *     (list=Expression weights=Expression)
	 * </pre>
	 */
	protected void sequence_Operator(ISerializationContext context, WeightedSumOp semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, formulaKPIPackage.Literals.WEIGHTED_SUM_OP__LIST) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, formulaKPIPackage.Literals.WEIGHTED_SUM_OP__LIST));
			if (transientValues.isValueTransient(semanticObject, formulaKPIPackage.Literals.WEIGHTED_SUM_OP__WEIGHTS) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, formulaKPIPackage.Literals.WEIGHTED_SUM_OP__WEIGHTS));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getOperatorAccess().getListExpressionParserRuleCall_3_3_0(), semanticObject.getList());
		feeder.accept(grammarAccess.getOperatorAccess().getWeightsExpressionParserRuleCall_3_5_0(), semanticObject.getWeights());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     TopLevelExpression returns Or
	 *     Expression returns Or
	 *     Or returns Or
	 *     Or.Or_1_0 returns Or
	 *     And returns Or
	 *     And.And_1_0 returns Or
	 *     Equality returns Or
	 *     Equality.Equality_1_0_0_0 returns Or
	 *     Equality.Inequality_1_0_1_0 returns Or
	 *     Comparison returns Or
	 *     Comparison.GreaterEq_1_0_0_0 returns Or
	 *     Comparison.LessEq_1_0_1_0 returns Or
	 *     Comparison.Greater_1_0_2_0 returns Or
	 *     Comparison.Less_1_0_3_0 returns Or
	 *     PlusOrMinus returns Or
	 *     PlusOrMinus.Plus_1_0_0_0 returns Or
	 *     PlusOrMinus.Minus_1_0_1_0 returns Or
	 *     MulOrDiv returns Or
	 *     MulOrDiv.Multiply_1_0_0_0 returns Or
	 *     MulOrDiv.Divide_1_0_1_0 returns Or
	 *     Operator returns Or
	 *     Primary returns Or
	 *
	 * Constraint:
	 *     (left=Or_Or_1_0 right=And)
	 * </pre>
	 */
	protected void sequence_Or(ISerializationContext context, Or semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, formulaKPIPackage.Literals.BIN_OP__LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, formulaKPIPackage.Literals.BIN_OP__LEFT));
			if (transientValues.isValueTransient(semanticObject, formulaKPIPackage.Literals.BIN_OP__RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, formulaKPIPackage.Literals.BIN_OP__RIGHT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getOrAccess().getOrLeftAction_1_0(), semanticObject.getLeft());
		feeder.accept(grammarAccess.getOrAccess().getRightAndParserRuleCall_1_2_0(), semanticObject.getRight());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     TopLevelExpression returns Minus
	 *     Expression returns Minus
	 *     Or returns Minus
	 *     Or.Or_1_0 returns Minus
	 *     And returns Minus
	 *     And.And_1_0 returns Minus
	 *     Equality returns Minus
	 *     Equality.Equality_1_0_0_0 returns Minus
	 *     Equality.Inequality_1_0_1_0 returns Minus
	 *     Comparison returns Minus
	 *     Comparison.GreaterEq_1_0_0_0 returns Minus
	 *     Comparison.LessEq_1_0_1_0 returns Minus
	 *     Comparison.Greater_1_0_2_0 returns Minus
	 *     Comparison.Less_1_0_3_0 returns Minus
	 *     PlusOrMinus returns Minus
	 *     PlusOrMinus.Plus_1_0_0_0 returns Minus
	 *     PlusOrMinus.Minus_1_0_1_0 returns Minus
	 *     MulOrDiv returns Minus
	 *     MulOrDiv.Multiply_1_0_0_0 returns Minus
	 *     MulOrDiv.Divide_1_0_1_0 returns Minus
	 *     Operator returns Minus
	 *     Primary returns Minus
	 *
	 * Constraint:
	 *     (left=PlusOrMinus_Minus_1_0_1_0 right=MulOrDiv)
	 * </pre>
	 */
	protected void sequence_PlusOrMinus(ISerializationContext context, Minus semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, formulaKPIPackage.Literals.BIN_OP__LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, formulaKPIPackage.Literals.BIN_OP__LEFT));
			if (transientValues.isValueTransient(semanticObject, formulaKPIPackage.Literals.BIN_OP__RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, formulaKPIPackage.Literals.BIN_OP__RIGHT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getPlusOrMinusAccess().getMinusLeftAction_1_0_1_0(), semanticObject.getLeft());
		feeder.accept(grammarAccess.getPlusOrMinusAccess().getRightMulOrDivParserRuleCall_1_1_0(), semanticObject.getRight());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     TopLevelExpression returns Plus
	 *     Expression returns Plus
	 *     Or returns Plus
	 *     Or.Or_1_0 returns Plus
	 *     And returns Plus
	 *     And.And_1_0 returns Plus
	 *     Equality returns Plus
	 *     Equality.Equality_1_0_0_0 returns Plus
	 *     Equality.Inequality_1_0_1_0 returns Plus
	 *     Comparison returns Plus
	 *     Comparison.GreaterEq_1_0_0_0 returns Plus
	 *     Comparison.LessEq_1_0_1_0 returns Plus
	 *     Comparison.Greater_1_0_2_0 returns Plus
	 *     Comparison.Less_1_0_3_0 returns Plus
	 *     PlusOrMinus returns Plus
	 *     PlusOrMinus.Plus_1_0_0_0 returns Plus
	 *     PlusOrMinus.Minus_1_0_1_0 returns Plus
	 *     MulOrDiv returns Plus
	 *     MulOrDiv.Multiply_1_0_0_0 returns Plus
	 *     MulOrDiv.Divide_1_0_1_0 returns Plus
	 *     Operator returns Plus
	 *     Primary returns Plus
	 *
	 * Constraint:
	 *     (left=PlusOrMinus_Plus_1_0_0_0 right=MulOrDiv)
	 * </pre>
	 */
	protected void sequence_PlusOrMinus(ISerializationContext context, Plus semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, formulaKPIPackage.Literals.BIN_OP__LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, formulaKPIPackage.Literals.BIN_OP__LEFT));
			if (transientValues.isValueTransient(semanticObject, formulaKPIPackage.Literals.BIN_OP__RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, formulaKPIPackage.Literals.BIN_OP__RIGHT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getPlusOrMinusAccess().getPlusLeftAction_1_0_0_0(), semanticObject.getLeft());
		feeder.accept(grammarAccess.getPlusOrMinusAccess().getRightMulOrDivParserRuleCall_1_1_0(), semanticObject.getRight());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     TopLevelExpression returns Not
	 *     Expression returns Not
	 *     Or returns Not
	 *     Or.Or_1_0 returns Not
	 *     And returns Not
	 *     And.And_1_0 returns Not
	 *     Equality returns Not
	 *     Equality.Equality_1_0_0_0 returns Not
	 *     Equality.Inequality_1_0_1_0 returns Not
	 *     Comparison returns Not
	 *     Comparison.GreaterEq_1_0_0_0 returns Not
	 *     Comparison.LessEq_1_0_1_0 returns Not
	 *     Comparison.Greater_1_0_2_0 returns Not
	 *     Comparison.Less_1_0_3_0 returns Not
	 *     PlusOrMinus returns Not
	 *     PlusOrMinus.Plus_1_0_0_0 returns Not
	 *     PlusOrMinus.Minus_1_0_1_0 returns Not
	 *     MulOrDiv returns Not
	 *     MulOrDiv.Multiply_1_0_0_0 returns Not
	 *     MulOrDiv.Divide_1_0_1_0 returns Not
	 *     Operator returns Not
	 *     Primary returns Not
	 *
	 * Constraint:
	 *     expression=Primary
	 * </pre>
	 */
	protected void sequence_Primary(ISerializationContext context, Not semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, formulaKPIPackage.Literals.NOT__EXPRESSION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, formulaKPIPackage.Literals.NOT__EXPRESSION));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getPrimaryAccess().getExpressionPrimaryParserRuleCall_1_2_0(), semanticObject.getExpression());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     TopLevelExpression returns UnaryMinus
	 *     Expression returns UnaryMinus
	 *     Or returns UnaryMinus
	 *     Or.Or_1_0 returns UnaryMinus
	 *     And returns UnaryMinus
	 *     And.And_1_0 returns UnaryMinus
	 *     Equality returns UnaryMinus
	 *     Equality.Equality_1_0_0_0 returns UnaryMinus
	 *     Equality.Inequality_1_0_1_0 returns UnaryMinus
	 *     Comparison returns UnaryMinus
	 *     Comparison.GreaterEq_1_0_0_0 returns UnaryMinus
	 *     Comparison.LessEq_1_0_1_0 returns UnaryMinus
	 *     Comparison.Greater_1_0_2_0 returns UnaryMinus
	 *     Comparison.Less_1_0_3_0 returns UnaryMinus
	 *     PlusOrMinus returns UnaryMinus
	 *     PlusOrMinus.Plus_1_0_0_0 returns UnaryMinus
	 *     PlusOrMinus.Minus_1_0_1_0 returns UnaryMinus
	 *     MulOrDiv returns UnaryMinus
	 *     MulOrDiv.Multiply_1_0_0_0 returns UnaryMinus
	 *     MulOrDiv.Divide_1_0_1_0 returns UnaryMinus
	 *     Operator returns UnaryMinus
	 *     Primary returns UnaryMinus
	 *
	 * Constraint:
	 *     expression=Primary
	 * </pre>
	 */
	protected void sequence_Primary(ISerializationContext context, UnaryMinus semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, formulaKPIPackage.Literals.UNARY_MINUS__EXPRESSION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, formulaKPIPackage.Literals.UNARY_MINUS__EXPRESSION));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getPrimaryAccess().getExpressionPrimaryParserRuleCall_2_2_0(), semanticObject.getExpression());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     ValueType returns RealValue
	 *     RealValue returns RealValue
	 *
	 * Constraint:
	 *     {RealValue}
	 * </pre>
	 */
	protected void sequence_RealValue(ISerializationContext context, RealValue semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Operation returns StandardDeviation
	 *     StandardDeviation returns StandardDeviation
	 *
	 * Constraint:
	 *     {StandardDeviation}
	 * </pre>
	 */
	protected void sequence_StandardDeviation(ISerializationContext context, StandardDeviation semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     ValueType returns TextualValue
	 *     TextualValue returns TextualValue
	 *
	 * Constraint:
	 *     {TextualValue}
	 * </pre>
	 */
	protected void sequence_TextualValue(ISerializationContext context, TextualValue semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     ValueType returns UnitValue
	 *     UnitValue returns UnitValue
	 *
	 * Constraint:
	 *     unit=ValueUnit
	 * </pre>
	 */
	protected void sequence_UnitValue(ISerializationContext context, UnitValue semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, formulaKPIPackage.Literals.UNIT_VALUE__UNIT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, formulaKPIPackage.Literals.UNIT_VALUE__UNIT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getUnitValueAccess().getUnitValueUnitEnumRuleCall_0(), semanticObject.getUnit());
		feeder.finish();
	}
	
	
}
