/*
 * generated by Xtext 2.41.0
 */
package lu.list.swrdi.formulaKPI.serializer;

import com.google.inject.Inject;
import java.util.List;
import lu.list.swrdi.formulaKPI.services.KPIFormulaDSLGrammarAccess;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;

@SuppressWarnings("all")
public class KPIFormulaDSLSyntacticSequencer extends AbstractSyntacticSequencer {

	protected KPIFormulaDSLGrammarAccess grammarAccess;
	protected AbstractElementAlias match_Primary_LeftParenthesisKeyword_0_0_a;
	protected AbstractElementAlias match_Primary_LeftParenthesisKeyword_0_0_p;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (KPIFormulaDSLGrammarAccess) access;
		match_Primary_LeftParenthesisKeyword_0_0_a = new TokenAlias(true, true, grammarAccess.getPrimaryAccess().getLeftParenthesisKeyword_0_0());
		match_Primary_LeftParenthesisKeyword_0_0_p = new TokenAlias(true, false, grammarAccess.getPrimaryAccess().getLeftParenthesisKeyword_0_0());
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_Primary_LeftParenthesisKeyword_0_0_a.equals(syntax))
				emit_Primary_LeftParenthesisKeyword_0_0_a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Primary_LeftParenthesisKeyword_0_0_p.equals(syntax))
				emit_Primary_LeftParenthesisKeyword_0_0_p(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     '('*
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) '!' expression=Primary
	 *     (rule start) (ambiguity) '-' expression=Primary
	 *     (rule start) (ambiguity) 'AVERAGE' '(' list=Expression
	 *     (rule start) (ambiguity) 'MAX' '(' list=Expression
	 *     (rule start) (ambiguity) 'MIN' '(' list=Expression
	 *     (rule start) (ambiguity) 'THRESHOLD' '(' expression=Expression
	 *     (rule start) (ambiguity) 'WEIGHTED_SUM' '(' list=Expression
	 *     (rule start) (ambiguity) '[' elements+=Expression
	 *     (rule start) (ambiguity) 'accumulator' (rule start)
	 *     (rule start) (ambiguity) 'do' expression=TopLevelExpression
	 *     (rule start) (ambiguity) 'filter' expression=TopLevelExpression
	 *     (rule start) (ambiguity) 'reduce' expression=TopLevelExpression
	 *     (rule start) (ambiguity) '|' expression=Expression
	 *     (rule start) (ambiguity) computable=[Computable|ID]
	 *     (rule start) (ambiguity) literal=[EnumerationLiteral|FQN]
	 *     (rule start) (ambiguity) value='false'
	 *     (rule start) (ambiguity) value='true'
	 *     (rule start) (ambiguity) value=DOUBLE
	 *     (rule start) (ambiguity) value=INT
	 *     (rule start) (ambiguity) value=STRING
	 *     (rule start) (ambiguity) {And.left=}
	 *     (rule start) (ambiguity) {Divide.left=}
	 *     (rule start) (ambiguity) {Equality.left=}
	 *     (rule start) (ambiguity) {Greater.left=}
	 *     (rule start) (ambiguity) {GreaterEq.left=}
	 *     (rule start) (ambiguity) {Inequality.left=}
	 *     (rule start) (ambiguity) {Less.left=}
	 *     (rule start) (ambiguity) {LessEq.left=}
	 *     (rule start) (ambiguity) {Minus.left=}
	 *     (rule start) (ambiguity) {Multiply.left=}
	 *     (rule start) (ambiguity) {Or.left=}
	 *     (rule start) (ambiguity) {Plus.left=}
	 
	 * </pre>
	 */
	protected void emit_Primary_LeftParenthesisKeyword_0_0_a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     '('+
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) 'AVERAGE' '(' list=Expression
	 *     (rule start) (ambiguity) 'MAX' '(' list=Expression
	 *     (rule start) (ambiguity) 'MIN' '(' list=Expression
	 *     (rule start) (ambiguity) 'THRESHOLD' '(' expression=Expression
	 *     (rule start) (ambiguity) 'WEIGHTED_SUM' '(' list=Expression
	 *     (rule start) (ambiguity) '[' elements+=Expression
	 *     (rule start) (ambiguity) 'do' expression=TopLevelExpression
	 *     (rule start) (ambiguity) 'filter' expression=TopLevelExpression
	 *     (rule start) (ambiguity) 'reduce' expression=TopLevelExpression
	 *     (rule start) (ambiguity) '|' expression=Expression
	 *     (rule start) (ambiguity) {And.left=}
	 *     (rule start) (ambiguity) {Divide.left=}
	 *     (rule start) (ambiguity) {Equality.left=}
	 *     (rule start) (ambiguity) {Greater.left=}
	 *     (rule start) (ambiguity) {GreaterEq.left=}
	 *     (rule start) (ambiguity) {Inequality.left=}
	 *     (rule start) (ambiguity) {Less.left=}
	 *     (rule start) (ambiguity) {LessEq.left=}
	 *     (rule start) (ambiguity) {Minus.left=}
	 *     (rule start) (ambiguity) {Multiply.left=}
	 *     (rule start) (ambiguity) {Or.left=}
	 *     (rule start) (ambiguity) {Plus.left=}
	 
	 * </pre>
	 */
	protected void emit_Primary_LeftParenthesisKeyword_0_0_p(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
