/*
 * generated by Xtext 2.41.0
 */
package lu.list.swrdi.formulaKPI.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class KPIFormulaDSLUiModule extends AbstractKPIFormulaDSLUiModule {

	public KPIFormulaDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
