/*
 * generated by Xtext 2.41.0
 */
package lu.list.swrdi.formulaKPI.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class KPIFormulaDSLAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("lu/list/swrdi/formulaKPI/parser/antlr/internal/InternalKPIFormulaDSL.tokens");
	}
}
