/*
 * generated by Xtext 2.41.0
 */
package lu.list.swrdi.formulaKPI.parser.antlr;

import com.google.inject.Inject;
import lu.list.swrdi.formulaKPI.parser.antlr.internal.InternalKPIFormulaDSLParser;
import lu.list.swrdi.formulaKPI.services.KPIFormulaDSLGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class KPIFormulaDSLParser extends AbstractAntlrParser {

	@Inject
	private KPIFormulaDSLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalKPIFormulaDSLParser createParser(XtextTokenStream stream) {
		return new InternalKPIFormulaDSLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "KPIFormulaDSL";
	}

	public KPIFormulaDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(KPIFormulaDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
