/*
 * generated by Xtext 2.41.0
 */
package lu.list.swrdi.formulaKPI;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class KPIFormulaDSLStandaloneSetup extends KPIFormulaDSLStandaloneSetupGenerated {

	public static void doSetup() {
		new KPIFormulaDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
