/*
 * generated by Xtext 2.41.0
 */
package lu.list.swrdi.formulaKPI;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class KPIFormulaDSLRuntimeModule extends AbstractKPIFormulaDSLRuntimeModule {
}
